/**
 * Phase 3.4 Step 2 — Proposal extraction prompt + library.
 *
 * Mirrors src/lib/ingestion/classify.ts shape:
 *   - callClaude wrapper, function_type='proposal_extract'
 *   - Ephemeral cache_control on system prompt (cache reuse across the
 *     5-fixture eval and live runs)
 *   - Returns structured JSON; library normalizes dollars → cents
 *
 * Extraction targets are documented in the system prompt below; the
 * shape returned to the caller is `ParsedProposal`. The raw Claude
 * output (pre-normalization) is preserved on `ParsedProposal.raw_response`
 * so the /api/proposals/extract route can write it to
 * proposals.raw_extraction JSONB without a second AI round-trip.
 *
 * Hot-path boundary (Addendum-B): no changes to match-item.ts,
 * commit-line-to-spine.ts, extract-invoice.ts, or correct-line.ts.
 * This module is a new surface — not a modification of the existing
 * matcher pipeline.
 */

import Anthropic from "@anthropic-ai/sdk";
import { callClaude } from "@/lib/claude";

// ─────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────

export type ExtractProposalInput = {
  pdfBuffer: Buffer | ArrayBuffer;
  /** document_extractions.id, surfaced via api_usage.metadata for debugging. */
  documentId?: string;
};

export type ExtractProposalMeta = {
  org_id: string;
  user_id?: string | null;
  metadata?: Record<string, unknown>;
};

/**
 * Per-line item shape AFTER dollars→cents normalization. The `*_cents`
 * fields are integers (or null when the proposal didn't break out the
 * category — never inferred). `attributes` carries free-form structured
 * specs (species, grade, dimensions) when the line is material-based.
 */
export type ParsedProposalLineItem = {
  line_number: number;
  description: string;
  description_normalized: string | null;
  quantity: number | null;
  unit_of_measure: string | null;
  unit_price_cents: number | null;
  total_price_cents: number;
  cost_code_suggestion: string | null;
  material_cost_cents: number | null;
  labor_cost_cents: number | null;
  subcontract_cost_cents: number | null;
  tax_cents: number | null;
  delivery_cents: number | null;
  notes_cents: number | null;
  attributes: Record<string, unknown>;
};

export type ParsedProposal = {
  // Header
  vendor_name: string;
  vendor_address: string | null;
  proposal_number: string | null;
  proposal_date: string | null; // YYYY-MM-DD
  valid_through: string | null; // YYYY-MM-DD

  // Generated by AI from header content
  title: string;

  // Total
  total_cents: number;

  // Scope
  scope_summary: string;
  inclusions: string | null;
  exclusions: string | null;
  notes: string | null;

  // Vendor schedule — explicit only, never inferred
  vendor_stated_start_date: string | null;
  vendor_stated_duration_days: number | null;

  // Lines
  line_items: ParsedProposalLineItem[];

  // Confidence
  confidence_score: number; // [0, 1]
  confidence_details: Record<string, number>;

  // Concerns flagged by the model (e.g. 'lump_sum', 'math_mismatch')
  flags: string[];

  // Pre-normalization Claude payload — written to proposals.raw_extraction
  // JSONB so the audit trail keeps the dollars-shape exactly as returned.
  raw_response: unknown;
};

// ─────────────────────────────────────────────────────────────────
// System prompt — exported for prompt-iteration eval (Step 6B)
// ─────────────────────────────────────────────────────────────────

export const PROPOSAL_EXTRACT_SYSTEM_PROMPT = `You are a construction proposal extractor for Nightwork, an operations platform used by custom home builders, remodelers, and commercial contractors. The attached document has already been classified as a proposal (a bid, quote, estimate, or scope-of-work issued BEFORE work has been performed). Your job is to extract structured data so a project manager can review and convert it into a purchase order.

TASK

Return a single STRICT JSON object matching the schema at the bottom. No prose. No markdown fences. No explanation. Only the JSON.

VENDOR ATTRIBUTION (CRITICAL)

The vendor is the SENDER of the proposal — the subcontractor, supplier, or trade partner offering work to the contractor (Ross Built or another builder). The vendor is NOT the recipient.

Look for the vendor at:
- The company letterhead or logo at the top of page 1
- A "From:" / "Issued by:" / "Submitted by:" line
- The signature block at the bottom of the proposal
- Return-mail address on a printed letterhead

Do NOT use:
- The "To:" / "Bill To:" / "Customer:" / "Client:" block — that's the contractor (recipient)
- Job site addresses or project names — those identify the project, not the vendor

If the proposal is on the contractor's letterhead but appears to be a sub-issued proposal (e.g. it has been forwarded), use the actual sender — the original subcontractor — as vendor_name. If you cannot identify a clean vendor sender, set vendor_name to your best inference and lower confidence_details.vendor_name.

PROPOSAL NUMBER

Some proposals have a number ("Proposal #12345", "Quote No. Q-2024-118", "Estimate #88-A"); some don't. If absent, set proposal_number to null and add "no_proposal_number" to flags. Do NOT fabricate a number from job IDs, project codes, or dates.

DATES

- proposal_date: when the vendor issued the proposal (sender's date). Format YYYY-MM-DD. If the proposal shows a date range, use the start. If no date is visible, set null.
- valid_through: explicit expiration only. Examples: "Valid until 2026-03-30", "Quote good for 30 days from 2026-02-15" (compute valid_through). If the validity period is not stated, set null. Do NOT default to "30 days from proposal_date" — vendors set their own validity windows.

VENDOR SCHEDULE — NEVER INFER

- vendor_stated_start_date: ONLY when the proposal explicitly states a start date the vendor commits to ("work to begin 2026-04-15", "scheduled start: April 15, 2026"). NEVER infer from valid_through, proposal_date, or scope size. If the vendor doesn't state it, set null.
- vendor_stated_duration_days: ONLY when the proposal explicitly states a duration ("14 working days", "3 weeks", "45 calendar days"). Convert weeks → days by ×7 and months → days by ×30. NEVER estimate duration from scope size, line count, or dollar amount. If the vendor doesn't state it, set null.

If the proposal makes vague schedule references ("when weather permits", "subject to material lead time") without explicit start/duration, leave both null and add "schedule_unclear" to flags.

TITLE GENERATION

Generate a short title summarizing the proposal:
"<trade> proposal — <vendor short name> — <YYYY-MM-DD>"

Examples:
- "Stucco proposal — Faust — 2026-01-15"
- "Roofing — KL Roof — 2025-03-19"
- "Concrete — ML — 2025-05-01"
- "Garage doors — Banko — 2025-09-26"

Use the trade if obvious from scope (concrete, framing, electrical, plumbing, roofing, drywall, stucco, paint, tile, flooring, HVAC, landscape, doors, windows). Use a short form of the vendor name (drop "LLC", "Inc", "Construction"). Use proposal_date if present; otherwise omit the trailing " — YYYY-MM-DD".

The proposals table requires a non-null title — never return an empty string. If the trade is unclear, fall back to "Proposal — <vendor short name>".

TOTALS

- total_amount: the proposal's grand total in DOLLARS (a number, not a string, no currency symbols). If the proposal has subtotal + tax shown separately, total_amount INCLUDES tax. If tax is unspecified or zero, total_amount equals subtotal.
- Line items must sum to within $1.00 of total_amount. If they don't, add "math_mismatch" to flags AND keep total_amount as stated on the proposal (don't recompute).
- If no clear grand total appears, sum line items as your best estimate, lower confidence_score, and add "missing_total" to flags.

LINE ITEMS

For every line in the proposal, return an object in line_items:
- line_number: 1-indexed position in the proposal (in the order shown)
- description: the original text from the PDF, verbatim
- description_normalized: a cleaned/standardized form (e.g. "2x4 SPF stud KD 92-5/8" if the proposal says "2x4 SPF KD studs - 92-5/8 inch length"). For non-material lines (labor, services), normalize for clarity but keep the trade context. Set null if the description is already clean.
- quantity: numeric only (e.g. 12, 2.5, 100). Null if the proposal lists no quantity.
- unit_of_measure: short form — EA, LF, SF, CY, CF, hr, day, lot, etc. Null if not stated.
- unit_price: per-unit price in DOLLARS. Null when the proposal is lump-sum (no unit price, only a total).
- amount: line total in DOLLARS. Always present.
- cost_code_suggestion: a free-text trade label your best guess based on description (e.g. "Concrete - foundation", "Stucco - exterior", "Plumbing - rough", "Electrical - finish"). Null if the trade is genuinely unclear. Be specific where you can — "Concrete - foundation" beats "Concrete".

COST BREAKDOWN — EXPLICIT ONLY, NEVER FABRICATE

These six fields are populated ONLY when the proposal explicitly separates the categories on the line:
- material_cost: dollars of material cost shown
- labor_cost: dollars of labor cost shown
- subcontract_cost: dollars of subcontracted work shown
- tax: dollars of tax shown
- delivery: dollars of delivery / freight shown
- notes_amount: dollars of any other category (markup, fees, contingency)

If the proposal is a lump-sum line ("Stucco - 4,000 SF: $48,000") with no breakdown, return ALL six as null. NEVER infer "this is probably 60% material and 40% labor" — if the proposal doesn't say, null is correct. Inferred breakdowns destroy the cost intelligence layer's ability to learn real material/labor splits.

ATTRIBUTES

For material-based lines, capture structured specs in attributes:
- "2x4 SPF stud KD 92-5/8" → {species: "SPF", grade: "stud", treatment: "KD", dimension: "2x4", length_in: 92.625}
- "3000 PSI concrete with fiber mesh" → {strength_psi: 3000, additive: "fiber mesh"}
- "Owens Corning 30-yr architectural shingle" → {manufacturer: "Owens Corning", type: "architectural", warranty_years: 30}

Use lowercase snake_case keys. Numeric values stay numeric. If the line is service/labor and there are no relevant specs, return an empty object {}.

SCOPE FIELDS

- scope_summary: 1-3 sentences describing what the vendor is offering. Always present.
- inclusions: bulleted text of what's included — only if the proposal has an "Includes:", "Scope of Work:", or similar section. Otherwise null. Preserve original bullet style or convert to "- item 1\\n- item 2".
- exclusions: bulleted text of what's excluded — only if the proposal has an "Excludes:", "Not Included:", "Allowance Excludes:", or similar section. Otherwise null.
- notes: any other freeform notes the proposal calls out (warranty terms, payment terms, conditions, special handling). Null if none.

CONFIDENCE

- confidence_score: overall 0.00-1.00 of how confident you are in the extraction. Use 0.85+ for clean structured proposals, 0.70-0.84 for proposals with minor ambiguity, below 0.70 for proposals with significant unclear fields.
- confidence_details: a flat object with per-field confidence:
  {
    "vendor_name": 0.95,
    "total_amount": 0.99,
    "line_items": 0.85,
    "cost_code_suggestions": 0.70
  }

FLAGS

Add string entries to flags as needed:
- "no_proposal_number" — proposal had no number
- "lump_sum" — single-line proposal with no itemization
- "math_mismatch" — line items don't sum to total
- "missing_total" — no clear grand total
- "vendor_unclear" — couldn't identify a clean vendor sender
- "schedule_unclear" — vague schedule references but no explicit start/duration
- "handwritten_detected" — handwritten content present
- "blurry_or_low_quality" — PDF image quality is poor
- "multi_trade" — proposal spans multiple trades

OUTPUT SCHEMA

Return ONLY this JSON shape (dollars are numbers, not strings; no markdown fences; no prose):

{
  "vendor_name": "string",
  "vendor_address": "string | null",
  "proposal_number": "string | null",
  "proposal_date": "YYYY-MM-DD | null",
  "valid_through": "YYYY-MM-DD | null",
  "title": "string",
  "total_amount": 0,
  "scope_summary": "string",
  "inclusions": "string | null",
  "exclusions": "string | null",
  "notes": "string | null",
  "vendor_stated_start_date": "YYYY-MM-DD | null",
  "vendor_stated_duration_days": 0,
  "line_items": [
    {
      "line_number": 1,
      "description": "string",
      "description_normalized": "string | null",
      "quantity": 0,
      "unit_of_measure": "string | null",
      "unit_price": 0,
      "amount": 0,
      "cost_code_suggestion": "string | null",
      "material_cost": 0,
      "labor_cost": 0,
      "subcontract_cost": 0,
      "tax": 0,
      "delivery": 0,
      "notes_amount": 0,
      "attributes": {}
    }
  ],
  "confidence_score": 0.0,
  "confidence_details": {},
  "flags": []
}

Numeric fields shown as 0 above accept null where the schema description says "Null if not stated" — emit literal null (not 0, not "null"). Other numeric fields are required (line_items[].amount, line_items[].line_number, total_amount).`;

// ─────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────

function stripCodeFences(text: string): string {
  return text.replace(/```json\s*/gi, "").replace(/```\s*/g, "").trim();
}

function toBuffer(input: Buffer | ArrayBuffer): Buffer {
  if (Buffer.isBuffer(input)) return input;
  return Buffer.from(input);
}

/**
 * Convert a dollar amount (number) to integer cents. Returns null when
 * the input is null/undefined/non-numeric. Uses Math.round to avoid
 * floating-point drift from `42.10 * 100 === 4209.999...`.
 *
 * Negative dollars permitted (credit memos / deductions). NaN/Infinity
 * coerce to null so downstream INSERTs don't blow up the BIGINT bound.
 */
export function dollarsToCents(value: unknown): number | null {
  if (value === null || value === undefined) return null;
  const n = typeof value === "number" ? value : Number(value);
  if (!Number.isFinite(n)) return null;
  return Math.round(n * 100);
}

/**
 * Same as dollarsToCents but throws when null/non-numeric — used for
 * required fields (line item amount, total) where we cannot fall through.
 */
function requireDollarsToCents(value: unknown, fieldName: string): number {
  const cents = dollarsToCents(value);
  if (cents === null) {
    throw new Error(`extractProposal: required field ${fieldName} is null or non-numeric (got ${JSON.stringify(value)})`);
  }
  return cents;
}

function clamp01(n: unknown): number {
  if (typeof n !== "number" || !Number.isFinite(n)) return 0;
  return Math.max(0, Math.min(1, n));
}

function asStringOrNull(v: unknown): string | null {
  if (typeof v === "string" && v.length > 0) return v;
  return null;
}

function asIntOrNull(v: unknown): number | null {
  if (typeof v !== "number" || !Number.isFinite(v)) return null;
  return Math.round(v);
}

function asNumberOrNull(v: unknown): number | null {
  if (typeof v !== "number" || !Number.isFinite(v)) return null;
  return v;
}

function asAttributes(v: unknown): Record<string, unknown> {
  if (v && typeof v === "object" && !Array.isArray(v)) {
    return v as Record<string, unknown>;
  }
  return {};
}

// ─────────────────────────────────────────────────────────────────
// normalizeProposal — pure transform (no I/O), tested directly
// ─────────────────────────────────────────────────────────────────

type RawLineItem = {
  line_number?: unknown;
  description?: unknown;
  description_normalized?: unknown;
  quantity?: unknown;
  unit_of_measure?: unknown;
  unit_price?: unknown;
  amount?: unknown;
  cost_code_suggestion?: unknown;
  material_cost?: unknown;
  labor_cost?: unknown;
  subcontract_cost?: unknown;
  tax?: unknown;
  delivery?: unknown;
  notes_amount?: unknown;
  attributes?: unknown;
};

type RawProposal = {
  vendor_name?: unknown;
  vendor_address?: unknown;
  proposal_number?: unknown;
  proposal_date?: unknown;
  valid_through?: unknown;
  title?: unknown;
  total_amount?: unknown;
  scope_summary?: unknown;
  inclusions?: unknown;
  exclusions?: unknown;
  notes?: unknown;
  vendor_stated_start_date?: unknown;
  vendor_stated_duration_days?: unknown;
  line_items?: unknown;
  confidence_score?: unknown;
  confidence_details?: unknown;
  flags?: unknown;
};

/**
 * Convert the AI's dollars-shape payload into the cents-shape ParsedProposal.
 * Throws on missing required fields (vendor_name, title, total_amount, per-line
 * description + amount) — these are not recoverable; the prompt is at fault.
 *
 * Exported so the eval (Step 6B) can re-run normalization against captured
 * raw responses without re-paying for AI calls.
 */
export function normalizeProposal(raw: RawProposal): ParsedProposal {
  if (typeof raw.vendor_name !== "string" || raw.vendor_name.length === 0) {
    throw new Error("extractProposal: vendor_name is missing or empty");
  }
  if (typeof raw.title !== "string" || raw.title.length === 0) {
    throw new Error("extractProposal: title is missing or empty");
  }
  if (typeof raw.scope_summary !== "string") {
    throw new Error("extractProposal: scope_summary is missing or non-string");
  }

  const totalCents = requireDollarsToCents(raw.total_amount, "total_amount");

  const rawLines = Array.isArray(raw.line_items) ? (raw.line_items as RawLineItem[]) : [];
  const line_items: ParsedProposalLineItem[] = rawLines.map((rl, idx) => {
    if (typeof rl.description !== "string" || rl.description.length === 0) {
      throw new Error(
        `extractProposal: line_items[${idx}].description is missing or empty`
      );
    }
    const lineNumber =
      typeof rl.line_number === "number" && Number.isFinite(rl.line_number)
        ? Math.round(rl.line_number)
        : idx + 1;
    return {
      line_number: lineNumber,
      description: rl.description,
      description_normalized: asStringOrNull(rl.description_normalized),
      quantity: asNumberOrNull(rl.quantity),
      unit_of_measure: asStringOrNull(rl.unit_of_measure),
      unit_price_cents: dollarsToCents(rl.unit_price),
      total_price_cents: requireDollarsToCents(rl.amount, `line_items[${idx}].amount`),
      cost_code_suggestion: asStringOrNull(rl.cost_code_suggestion),
      material_cost_cents: dollarsToCents(rl.material_cost),
      labor_cost_cents: dollarsToCents(rl.labor_cost),
      subcontract_cost_cents: dollarsToCents(rl.subcontract_cost),
      tax_cents: dollarsToCents(rl.tax),
      delivery_cents: dollarsToCents(rl.delivery),
      notes_cents: dollarsToCents(rl.notes_amount),
      attributes: asAttributes(rl.attributes),
    };
  });

  const confidenceDetails =
    raw.confidence_details &&
    typeof raw.confidence_details === "object" &&
    !Array.isArray(raw.confidence_details)
      ? (raw.confidence_details as Record<string, unknown>)
      : {};
  const cleanedConfidenceDetails: Record<string, number> = {};
  for (const [k, v] of Object.entries(confidenceDetails)) {
    if (typeof v === "number" && Number.isFinite(v)) {
      cleanedConfidenceDetails[k] = clamp01(v);
    }
  }

  const flagsArr = Array.isArray(raw.flags) ? raw.flags : [];
  const flags: string[] = flagsArr.filter((s): s is string => typeof s === "string");

  return {
    vendor_name: raw.vendor_name,
    vendor_address: asStringOrNull(raw.vendor_address),
    proposal_number: asStringOrNull(raw.proposal_number),
    proposal_date: asStringOrNull(raw.proposal_date),
    valid_through: asStringOrNull(raw.valid_through),
    title: raw.title,
    total_cents: totalCents,
    scope_summary: raw.scope_summary,
    inclusions: asStringOrNull(raw.inclusions),
    exclusions: asStringOrNull(raw.exclusions),
    notes: asStringOrNull(raw.notes),
    vendor_stated_start_date: asStringOrNull(raw.vendor_stated_start_date),
    vendor_stated_duration_days: asIntOrNull(raw.vendor_stated_duration_days),
    line_items,
    confidence_score: clamp01(raw.confidence_score),
    confidence_details: cleanedConfidenceDetails,
    flags,
    raw_response: raw,
  };
}

// ─────────────────────────────────────────────────────────────────
// extractProposal — public entry point
// ─────────────────────────────────────────────────────────────────

export async function extractProposal(
  input: ExtractProposalInput,
  meta: ExtractProposalMeta
): Promise<ParsedProposal> {
  const base64 = toBuffer(input.pdfBuffer).toString("base64");

  const systemBlocks: Anthropic.Messages.TextBlockParam[] = [
    {
      type: "text",
      text: PROPOSAL_EXTRACT_SYSTEM_PROMPT,
      cache_control: { type: "ephemeral" },
    },
  ];

  const userContent: Anthropic.Messages.ContentBlockParam[] = [
    {
      type: "document",
      source: {
        type: "base64",
        media_type: "application/pdf",
        data: base64,
      },
    },
    {
      type: "text",
      text: "Extract the attached construction proposal. Return only the JSON object.",
    },
  ];

  const response = await callClaude({
    model: "claude-sonnet-4-20250514",
    max_tokens: 4096,
    system: systemBlocks,
    messages: [{ role: "user", content: userContent }],
    function_type: "proposal_extract",
    org_id: meta.org_id,
    user_id: meta.user_id ?? null,
    metadata: { ...meta.metadata, document_id: input.documentId },
  });

  const textBlock = response.content.find((block) => block.type === "text");
  if (!textBlock || textBlock.type !== "text") {
    throw new Error("Proposal extractor returned no text content block");
  }

  const cleaned = stripCodeFences(textBlock.text);
  let parsed: RawProposal;
  try {
    parsed = JSON.parse(cleaned) as RawProposal;
  } catch (err) {
    const msg = err instanceof Error ? err.message : "unknown";
    throw new Error(
      `Proposal extractor returned invalid JSON: ${msg}. First 200 chars: ${cleaned.slice(0, 200)}`
    );
  }

  return normalizeProposal(parsed);
}
