/**
 * Phase 3.4 Step 2 — Proposal extraction prompt + library.
 *
 * Mirrors src/lib/ingestion/classify.ts shape:
 *   - callClaude wrapper, function_type='proposal_extract'
 *   - Ephemeral cache_control on system prompt (cache reuse across the
 *     5-fixture eval and live runs)
 *   - Returns structured JSON; library normalizes dollars → cents
 *
 * Extraction targets are documented in the system prompt below; the
 * shape returned to the caller is `ParsedProposal`. The raw Claude
 * output (pre-normalization) is preserved on `ParsedProposal.raw_response`
 * so the /api/proposals/extract route can write it to
 * proposals.raw_extraction JSONB without a second AI round-trip.
 *
 * Hot-path boundary (Addendum-B): no changes to match-item.ts,
 * commit-line-to-spine.ts, extract-invoice.ts, or correct-line.ts.
 * This module is a new surface — not a modification of the existing
 * matcher pipeline.
 */

import Anthropic from "@anthropic-ai/sdk";
import { callClaude } from "@/lib/claude";

// ─────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────

export type ExtractProposalInput = {
  pdfBuffer: Buffer | ArrayBuffer;
  /** document_extractions.id, surfaced via api_usage.metadata for debugging. */
  documentId?: string;
};

export type ExtractProposalMeta = {
  org_id: string;
  user_id?: string | null;
  metadata?: Record<string, unknown>;
};

/**
 * Per-line item shape AFTER dollars→cents normalization. The `*_cents`
 * fields are integers (or null when the proposal didn't break out the
 * category — never inferred). `attributes` carries free-form structured
 * specs (species, grade, dimensions) when the line is material-based.
 */
export type ParsedProposalLineItem = {
  line_number: number;
  description: string;
  description_normalized: string | null;
  quantity: number | null;
  unit_of_measure: string | null;
  unit_price_cents: number | null;
  total_price_cents: number;
  cost_code_suggestion: string | null;
  material_cost_cents: number | null;
  labor_cost_cents: number | null;
  subcontract_cost_cents: number | null;
  tax_cents: number | null;
  delivery_cents: number | null;
  notes_cents: number | null;
  attributes: Record<string, unknown>;
};

/**
 * Fee schedule entry — one row from a proposal's separate hourly /
 * blended rate table (common on professional-services proposals where
 * the base scope is a fixed fee but additional time is billed per
 * hour). Phase 3.4 Step 5b/5c.
 */
export type ParsedProposalFeeScheduleEntry = {
  rate_type: string; // short slug, e.g. "hourly", "principal_hour"
  description: string | null;
  rate_cents: number | null;
  unit: string | null; // "hr", "day", "visit", etc.
};

/**
 * Payment schedule entry — one billing milestone with either a
 * percentage of total, a dollar amount, or both. Phase 3.4 Step 5b/5c.
 */
export type ParsedProposalPaymentScheduleEntry = {
  milestone: string; // short slug, e.g. "deposit", "delivery"
  percentage_pct: number | null;
  amount_cents: number | null;
  trigger: string | null; // when the payment is owed
};

/**
 * Payment terms object — top-level vendor billing terms. Each sub-field
 * nullable; populate only fields explicitly stated on the proposal.
 * Phase 3.4 Step 5b/5c.
 */
export type ParsedProposalPaymentTerms = {
  net_days: number | null;
  late_interest_rate_pct: number | null;
  governing_law: string | null;
  other_terms_text: string | null;
};

/**
 * Schedule item — one structured chunk of a phased / sequenced proposal
 * scope. Phase 4 schedule-intelligence foundation per amendment-1.
 * Captured at proposal extract time (Step 5g); surfaced when Phase 3.5
 * ships the PO detail tab. Phase 3.4 Step 5f/5g.
 */
export type ParsedProposalScheduleItem = {
  scope_item: string;
  linked_line_number: number | null;
  estimated_start_date: string | null; // YYYY-MM-DD
  estimated_duration_days: number | null;
  sequence_position: number | null;
  depends_on: number[];
  responsibility: string | null; // "vendor" | "contractor" | "shared"
  deliverables: string[];
  trigger: string | null;
};

export type ParsedProposal = {
  // Header
  vendor_name: string;
  vendor_address: string | null;
  proposal_number: string | null;
  proposal_date: string | null; // YYYY-MM-DD
  valid_through: string | null; // YYYY-MM-DD

  // Generated by AI from header content
  title: string;

  // Total
  total_cents: number;

  // Scope
  scope_summary: string;
  inclusions: string | null;
  exclusions: string | null;
  notes: string | null;

  // Vendor schedule — explicit only, never inferred
  vendor_stated_start_date: string | null;
  vendor_stated_duration_days: number | null;

  // Lines
  line_items: ParsedProposalLineItem[];

  // Fee + payment structures (Phase 3.4 Step 5b/5c). Each is null when
  // the proposal doesn't include the structure; never inferred. Mirror
  // the migration 00088 column shape so commit can persist directly.
  additional_fee_schedule: ParsedProposalFeeScheduleEntry[] | null;
  payment_schedule: ParsedProposalPaymentScheduleEntry[] | null;
  payment_terms: ParsedProposalPaymentTerms | null;

  // Schedule intelligence + acceptance signature (Phase 3.4 Step 5f/5g).
  // schedule_items: null when no schedulable structure on proposal.
  // accepted_signature_*: name/date null when block blank or absent;
  // present is the load-bearing boolean (NOT NULL on the column).
  schedule_items: ParsedProposalScheduleItem[] | null;
  accepted_signature_present: boolean;
  accepted_signature_name: string | null;
  accepted_signature_date: string | null;

  // Project/install/site address (Phase 3.4 Step 5j/5k). Null when
  // proposal doesn't state a site address.
  job_address: string | null;

  // Confidence
  confidence_score: number; // [0, 1]
  confidence_details: Record<string, number>;

  // Concerns flagged by the model (e.g. 'lump_sum', 'math_mismatch')
  flags: string[];

  // Pre-normalization Claude payload — written to proposals.raw_extraction
  // JSONB so the audit trail keeps the dollars-shape exactly as returned.
  raw_response: unknown;
};

// ─────────────────────────────────────────────────────────────────
// System prompt — exported for prompt-iteration eval (Step 6B)
// ─────────────────────────────────────────────────────────────────

export const PROPOSAL_EXTRACT_SYSTEM_PROMPT = `You are a construction proposal extractor for Nightwork, an operations platform used by custom home builders, remodelers, and commercial contractors. The attached document has already been classified as a proposal (a bid, quote, estimate, or scope-of-work issued BEFORE work has been performed). Your job is to extract structured data so a project manager can review and convert it into a purchase order.

TASK

Return a single STRICT JSON object matching the schema at the bottom. No prose. No markdown fences. No explanation. Only the JSON.

VENDOR ATTRIBUTION (CRITICAL)

The vendor is the SENDER of the proposal — the subcontractor, supplier, or trade partner offering work to the contractor (Ross Built or another builder). The vendor is NOT the recipient.

Look for the vendor at:
- The company letterhead or logo at the top of page 1
- A "From:" / "Issued by:" / "Submitted by:" line
- The signature block at the bottom of the proposal
- Return-mail address on a printed letterhead

Do NOT use:
- The "To:" / "Bill To:" / "Customer:" / "Client:" block — that's the contractor (recipient)
- Job site addresses or project names — those identify the project, not the vendor

If the proposal is on the contractor's letterhead but appears to be a sub-issued proposal (e.g. it has been forwarded), use the actual sender — the original subcontractor — as vendor_name. If you cannot identify a clean vendor sender, set vendor_name to your best inference and lower confidence_details.vendor_name.

PROPOSAL NUMBER

Some proposals have a number ("Proposal #12345", "Quote No. Q-2024-118", "Estimate #88-A"); some don't. If absent, set proposal_number to null and add "no_proposal_number" to flags. Do NOT fabricate a number from job IDs, project codes, or dates.

DATES

- proposal_date: when the vendor issued the proposal (sender's date). Format YYYY-MM-DD. If the proposal shows a date range, use the start. If no date is visible, set null.
- valid_through: HARD RULE — only populate when the PDF contains an explicit literal expiration date with month/day/year (e.g., "Valid through March 17, 2026", "Expires 03/17/2026", "Valid until 2026-03-30"). All other phrasings — "valid for X days", "subject to revision within X days", "good for X weeks", "expires 30 days after acceptance", "quote good for 30 days" — ALWAYS return null, regardless of whether a proposal_date is visible. Do not compute date arithmetic. Do not infer from context. If the proposal does not contain a literal expiration date, set null.

VENDOR SCHEDULE — NEVER INFER

- vendor_stated_start_date: ONLY when the proposal explicitly states a start date the vendor commits to ("work to begin 2026-04-15", "scheduled start: April 15, 2026"). NEVER infer from valid_through, proposal_date, or scope size. If the vendor doesn't state it, set null.
- vendor_stated_duration_days: ONLY when the proposal explicitly states a duration ("14 working days", "3 weeks", "45 calendar days"). Convert weeks → days by ×7 and months → days by ×30. NEVER estimate duration from scope size, line count, or dollar amount. If the vendor doesn't state it, set null.

If the proposal makes vague schedule references ("when weather permits", "subject to material lead time") without explicit start/duration, leave both null and add "schedule_unclear" to flags.

TITLE GENERATION

Generate a short title summarizing the proposal:
"<trade> proposal — <vendor short name> — <YYYY-MM-DD>"

Examples:
- "Stucco proposal — Faust — 2026-01-15"
- "Roofing — KL Roof — 2025-03-19"
- "Concrete — ML — 2025-05-01"
- "Garage doors — Banko — 2025-09-26"

Use the trade if obvious from scope (concrete, framing, electrical, plumbing, roofing, drywall, stucco, paint, tile, flooring, HVAC, landscape, doors, windows). Use a short form of the vendor name (drop "LLC", "Inc", "Construction"). Use proposal_date if present; otherwise omit the trailing " — YYYY-MM-DD".

The proposals table requires a non-null title — never return an empty string. If the trade is unclear, fall back to "Proposal — <vendor short name>".

TOTALS

- total_amount: the proposal's grand total in DOLLARS (a number, not a string, no currency symbols). If the proposal has subtotal + tax shown separately, total_amount INCLUDES tax. If tax is unspecified or zero, total_amount equals subtotal.
- Line items must sum to within $1.00 of total_amount. If they don't, add "math_mismatch" to flags AND keep total_amount as stated on the proposal (don't recompute).
- If no clear grand total appears, sum line items as your best estimate, lower confidence_score, and add "missing_total" to flags.

LINE ITEMS

For every line in the proposal, return an object in line_items:
- line_number: 1-indexed position in the proposal (in the order shown)
- description: the original text from the PDF, verbatim
- description_normalized: a cleaned/standardized form (e.g. "2x4 SPF stud KD 92-5/8" if the proposal says "2x4 SPF KD studs - 92-5/8 inch length"). For non-material lines (labor, services), normalize for clarity but keep the trade context. Set null if the description is already clean.
- quantity: numeric only (e.g. 12, 2.5, 100). Null if the proposal lists no quantity.
- unit_of_measure: short form — EA, LF, SF, CY, CF, hr, day, lot, etc. Null if not stated.
- unit_price: per-unit price in DOLLARS. Null when the proposal is lump-sum (no unit price, only a total).
- amount: line total in DOLLARS. Always present.

IMPLIED UoM EXTRACTION FROM DESCRIPTION

When a line description contains EXPLICIT measurement language ("approx 2300 sq ft", "~2000 SF of wall space", "440 LF of foundation", "10 windows", "3 doors", "200 LF of crown trim", "800 sq ft total"), use that as the line's quantity + unit_of_measure even when the PDF's literal Qty/Hours column says "1" or another value. The cost intelligence layer learns from $/UoM rates; storing "1 EA at $17,750" instead of "2300 SF at $7.72/SF" makes a T&G install rate invisible to similarity search across vendors. Reading the description for the real measurement is critical.

When you override the PDF's literal Qty column with a measurement extracted from the description, set attributes.qty_from_description = true on that line item. This signals to the PM that the qty/UoM came from description parsing rather than a structured Qty column — they can verify on review. Examples:

- Description "install supplied T&G ~2300 sq ft" + PDF Qty column "1" → qty=2300, unit_of_measure="SF", attributes.qty_from_description=true
- Description "install on 10 windows" + PDF Qty column "10" → qty=10, unit_of_measure="EA" (description and column agree, no flag needed — qty_from_description NOT set)
- Description "440 LF of foundation" + PDF Qty column "1" → qty=440, unit_of_measure="LF", attributes.qty_from_description=true
- Description "install baseboard trim" + PDF Qty column "180 LF" → qty=180, unit_of_measure="LF" (column was structured, no override needed)

When the description has no explicit measurement OR is ambiguous ("install crown trim throughout", "supply doors as listed"), use the PDF's literal Qty column as-is. Do not invent measurements.
- cost_code_suggestion: a free-text trade label your best guess based on description (e.g. "Concrete - foundation", "Stucco - exterior", "Plumbing - rough", "Electrical - finish"). Null if the trade is genuinely unclear. Be specific where you can — "Concrete - foundation" beats "Concrete". HARD RULE — set cost_code_suggestion to null on lines that are taxes, fees, project conditions, or general notes/conditions rather than billable trade work. Do NOT label these with synthetic cost-code-shaped strings like "Tax", "Materials - note", "Condition", or "Note". Lines that are notes/taxes/conditions get null here; the line itself can still exist (we mirror the PDF's table structure) but must not pretend to be cost-coded.

COST BREAKDOWN — EXPLICIT ONLY, NEVER FABRICATE

These six fields are populated ONLY when the proposal explicitly separates the categories on the line:
- material_cost: dollars of material cost shown
- labor_cost: dollars of labor cost shown
- subcontract_cost: dollars of subcontracted work shown
- tax: dollars of tax shown
- delivery: dollars of delivery / freight shown
- notes_amount: dollars of any other category (markup, fees, contingency)

If the proposal is a lump-sum line ("Stucco - 4,000 SF: $48,000") with no breakdown, return ALL six as null. NEVER infer "this is probably 60% material and 40% labor" — if the proposal doesn't say, null is correct. Inferred breakdowns destroy the cost intelligence layer's ability to learn real material/labor splits.

ATTRIBUTES

For material-based lines, capture structured specs in attributes:
- "2x4 SPF stud KD 92-5/8" → {species: "SPF", grade: "stud", treatment: "KD", dimension: "2x4", length_in: 92.625}
- "3000 PSI concrete with fiber mesh" → {strength_psi: 3000, additive: "fiber mesh"}
- "Owens Corning 30-yr architectural shingle" → {manufacturer: "Owens Corning", type: "architectural", warranty_years: 30}

Use lowercase snake_case keys. Numeric values stay numeric. If the line is service/labor and there are no relevant specs, return an empty object {}.

SCOPE FIELDS

- scope_summary: 1-3 sentences describing what the vendor is offering. Always present.
- inclusions: bulleted text of what's included. Populate when the proposal lists an explicit set of scope items, EVEN IF the section is not literally titled "Inclusions:". Common forms that count:
    * "Scope of Work:" with bulleted sub-items
    * "The following services are included in our [Phase N / scope]:" followed by bullets
    * Per-phase sub-bullets ("Phase I includes: Define Program, Site Inventory, Concept Plan")
    * "Includes:" / "Included:" headings
  Convert all of these to "- item 1\\n- item 2" form (one bullet per scope item). When the proposal has phased structure with per-phase inclusions, list ALL of them across phases, prefixing with the phase label (e.g. "- Phase I: Define Program"). Set null only when the proposal genuinely lists no scope items beyond the line-item descriptions themselves.
- exclusions: bulleted text of what's excluded — same broadening rule as inclusions. Look for "Excludes:", "Not Included:", "Allowance Excludes:", "The following are NOT included:", or any negative-scope list. Set null only when none stated.
- notes: any other freeform notes the proposal calls out (warranty terms, conditions, special handling). Null if none. NOTE: payment-related text belongs in payment_terms.other_terms_text, not here.

ADDITIONAL FEE SCHEDULE — STRUCTURED EXTRACTION

Many proposals (especially professional services like architecture, landscape design, engineering) include a SEPARATE table of hourly or blended rates for additional services beyond the base proposal scope. These are NOT base line items — they're rates the vendor will bill at if extra work is requested. Common forms:

  "Principal architect ........... $200/hr"
  "Drafter ......................... $90/hr"
  "Site visit fee ................. $750/visit"
  "Per diem expenses .............. $150/day"

When the proposal contains such a fee/rate table, populate additional_fee_schedule as an array. Each entry:
  {rate_type, description, rate, unit}

- rate_type: a short slug describing the rate, e.g. "principal_hour", "drafter_hour", "site_visit_fee", "per_diem", "hourly", "blended". Use lowercase snake_case.
- description: the literal label from the proposal, verbatim.
- rate: number in DOLLARS (a float, no currency symbol).
- unit: short form — "hr", "day", "visit", "ea", etc. Null if not stated.

If the proposal has no separate fee/rate table, set additional_fee_schedule to null. NEVER infer rates from line items, NEVER fabricate from market knowledge of what trades typically charge. Only populate when the proposal lists explicit rates as a separate structure.

PAYMENT SCHEDULE — STRUCTURED EXTRACTION

When the proposal specifies WHEN money is owed (a milestone-based billing breakdown separate from the line-item totals), capture payment_schedule as an array. Common forms:

  "50% deposit upon contract signing"
  "25% upon delivery of materials"
  "25% upon completion"

  "Phase I billed upon completion of phase. Phase II billed upon completion of phase."

  "$5,000 deposit. Balance due net 30 from completion."

Each entry:
  {milestone, percentage_pct, amount, trigger}

- milestone: short slug like "deposit", "delivery", "phase_1", "phase_2", "completion", "balance". Use lowercase snake_case.
- percentage_pct: 0-100 number (e.g., 50 for "50% deposit"). Null if proposal specifies a dollar amount instead.
- amount: dollars (a number). Null if proposal specifies a percentage instead. Both percentage_pct AND amount may be populated when the proposal states both (e.g., "50% ($10,000) deposit").
- trigger: text describing when the payment is owed — verbatim or close paraphrase, e.g., "upon contract signing", "upon delivery", "30 days from completion", "upon completion of Phase I".

If the proposal has no milestone-based billing (single payment, lump-sum due upon completion only) → set payment_schedule to null. NEVER infer milestones from the line items themselves; line items are the work breakdown, not the payment schedule.

PAYMENT TERMS — STRUCTURED EXTRACTION

Capture top-level vendor billing terms as a single payment_terms object:
  {net_days, late_interest_rate_pct, governing_law, other_terms_text}

- net_days: HARD RULE — only populate when the PDF contains explicit billing-credit language: "Net 30", "Net 15", "Net 60", "due 30 days from invoice date", "due within 30 days of invoice", "payment due within N days of invoice", "payment terms: 30 days", or "Due upon receipt" (= 0). The signal MUST be tied directly to the invoice payment due date.

  Examples that MUST return null (preserve the literal language in other_terms_text — never coerce these to a Net-N integer):
  - "due on the 10th of the month following invoicing" — month-end+10 billing convention, NOT Net-N
  - "quote good for 30 days" / "estimate pricing held for 30 days" / "valid for 30 days" / "pricing held for 30 days" — quote validity, NOT billing terms
  - "interest charged after thirty days" → use 30 ONLY if the context literally says "30 days from invoice" or equivalent past-due trigger; if the context is collection-action threshold, dispute resolution window, or general legal recourse timing, return null
  - "ninety days to commence collection" / "60 days to dispute" — collection / dispute thresholds, NOT billing terms
  - any "N days" reference NOT explicitly tied to invoice payment due date — when in doubt, return null

  When in doubt: return null and preserve the original phrasing in other_terms_text. A human will not be confused by null + the literal text; a human WILL be misled by a fabricated Net-N value.
- late_interest_rate_pct: number for late-payment interest (e.g., 1.5 for "1.5% per month" — convert annual rates to monthly if the proposal expresses them annually). Null if no late-interest clause.
- governing_law: text identifying the legal jurisdiction, e.g., "Florida law", "State of Florida". Null if not stated.
- other_terms_text: any other payment-related terms paragraph that doesn't fit above (retainage clauses, warranty payment conditions, lien-release requirements, deposit-non-refundable language, etc.). Use this for payment-adjacent text that previously would have ended up in the notes field. Null if none.

If the proposal has no terms section at all → set payment_terms to null at the top level. Don't return an object with all-null sub-fields. Same rule as everywhere: never infer; populate only fields explicitly stated on the proposal.

SCHEDULE ITEMS — STRUCTURED EXTRACTION (Phase 4 schedule intelligence)

Many proposals have an implicit schedule structure embedded in their scope: phases, deliverables, sequencing, durations, triggers. Capture this as schedule_items, an array of structured schedule entries. Phase 4 (schedule intelligence) will use these to learn realistic durations per trade per vendor; for now we just capture them.

Each entry shape:
  {
    "scope_item": "string",
    "linked_line_number": 1,
    "estimated_start_date": "YYYY-MM-DD | null",
    "estimated_duration_days": 0,
    "sequence_position": 1,
    "depends_on": [],
    "responsibility": "vendor | contractor | shared",
    "deliverables": [],
    "trigger": "string | null"
  }

- scope_item: short label for the scope chunk (e.g., "Phase I: Schematic Design", "Foundation pour", "Roof installation"). Use the proposal's own label.
- linked_line_number: the matching line_items[].line_number when there's a clear 1:1 link (e.g., the phased proposal has a line per phase). Null when no clean link.
- estimated_start_date: explicit start date if the proposal states one for this scope item. Most won't; null is common.
- estimated_duration_days: explicit duration in days if stated for this item (convert weeks → ×7, months → ×30). Null otherwise.
- sequence_position: 1-indexed position in the schedule (Phase I = 1, Phase II = 2, etc.). Use the proposal's own sequencing.
- depends_on: array of sequence_position numbers this scope item depends on (commonly the previous phase). Empty array when no dependency stated. NEVER infer dependencies the proposal doesn't state — capture only explicit predecessor/successor language.
- responsibility: "vendor" (the proposal sender does the work), "contractor" (Ross Built does it), or "shared". Most proposals are vendor-only. Use "shared" when the proposal explicitly calls out collaboration.
- deliverables: array of short labels for what this scope item produces (e.g., ["schematic plan", "concept presentation"]). Empty array when no specific deliverables stated.
- trigger: text describing when this scope item starts (e.g., "upon receipt of design fee", "after permit approval", "after foundation pour"). Null when no explicit trigger stated.

If the proposal has no schedulable scope structure (e.g., a single lump-sum line for "drywall on whole house, $12,500"), set schedule_items to null. NEVER fabricate phases the proposal doesn't list. Most multi-phase or multi-scope proposals will have schedule_items populated; most simple lump-sum or single-trade proposals will not.

ACCEPTANCE SIGNATURE — STRUCTURED EXTRACTION

Many vendor proposals include an "Accepted By" / "Signed By" / "Approved By" / signature block at the bottom for the contractor (Ross Built) to sign. Sometimes blank, sometimes filled in. Capture all three fields:

- accepted_signature_present: TRUE when the proposal PDF shows a signature block AND it has been filled in (a name and/or date have been written/typed in). FALSE when the block is blank, or no block exists at all. This is the load-bearing boolean — gates queries like "how many of our open proposals are signed?".

- accepted_signature_name: the literal name written/typed in the "Accepted By" / "Signed By" line. Null when blank or no signature block.

- accepted_signature_date: the date next to the acceptance signature, if present. Format YYYY-MM-DD. Null when blank, no signature block, or only the name is filled in but no date.

Do NOT confuse the acceptance signature with the vendor's own signature on the proposal (the sender). The acceptance is the RECIPIENT's signature accepting the proposal — it's the contractor side of the block.

If accepted_signature_present is FALSE, accepted_signature_name and accepted_signature_date should both be null.

JOB ADDRESS — STRUCTURED EXTRACTION

Most proposals reference an install/site/project address. Capture as job_address when the proposal explicitly states one, looking for any of:
- "Project Address:" / "Job Address:" / "Install Address:" / "Site Address:"
- The address line in a "Bill To:" / "Ship To:" / "Project:" block (when distinct from the contractor's office address)
- An address embedded near the project name (e.g., "501 74th Street, Holmes Beach, FL 34217" labeled as the project location)

Format: full address as written (street, city, state, zip — comma-separated as on the proposal). Preserve the vendor's literal text rather than canonicalizing.

Set job_address to null when the proposal does not name a site address (e.g., service-only proposals where work happens at multiple locations or no fixed site).

Do NOT use the vendor's own business/office address as job_address — that's vendor_address. job_address is the SITE where the work will be performed.

CONFIDENCE

- confidence_score: overall 0.00-1.00 of how confident you are in the extraction. Use 0.85+ for clean structured proposals, 0.70-0.84 for proposals with minor ambiguity, below 0.70 for proposals with significant unclear fields.
- confidence_details: a flat object with per-field confidence:
  {
    "vendor_name": 0.95,
    "total_amount": 0.99,
    "line_items": 0.85,
    "cost_code_suggestions": 0.70
  }

FLAGS

Add string entries to flags as needed:
- "no_proposal_number" — proposal had no number
- "lump_sum" — single-line proposal with no itemization
- "math_mismatch" — line items don't sum to total
- "missing_total" — no clear grand total
- "vendor_unclear" — couldn't identify a clean vendor sender
- "schedule_unclear" — vague schedule references but no explicit start/duration
- "handwritten_detected" — handwritten content present
- "blurry_or_low_quality" — PDF image quality is poor
- "multi_trade" — proposal spans multiple trades

OUTPUT SCHEMA

Return ONLY this JSON shape (dollars are numbers, not strings; no markdown fences; no prose):

{
  "vendor_name": "string",
  "vendor_address": "string | null",
  "proposal_number": "string | null",
  "proposal_date": "YYYY-MM-DD | null",
  "valid_through": "YYYY-MM-DD | null",
  "title": "string",
  "total_amount": 0,
  "scope_summary": "string",
  "inclusions": "string | null",
  "exclusions": "string | null",
  "notes": "string | null",
  "vendor_stated_start_date": "YYYY-MM-DD | null",
  "vendor_stated_duration_days": 0,
  "line_items": [
    {
      "line_number": 1,
      "description": "string",
      "description_normalized": "string | null",
      "quantity": 0,
      "unit_of_measure": "string | null",
      "unit_price": 0,
      "amount": 0,
      "cost_code_suggestion": "string | null",
      "material_cost": 0,
      "labor_cost": 0,
      "subcontract_cost": 0,
      "tax": 0,
      "delivery": 0,
      "notes_amount": 0,
      "attributes": {}
    }
  ],
  "additional_fee_schedule": [
    {
      "rate_type": "string",
      "description": "string | null",
      "rate": 0,
      "unit": "string | null"
    }
  ],
  "payment_schedule": [
    {
      "milestone": "string",
      "percentage_pct": 0,
      "amount": 0,
      "trigger": "string | null"
    }
  ],
  "payment_terms": {
    "net_days": 0,
    "late_interest_rate_pct": 0,
    "governing_law": "string | null",
    "other_terms_text": "string | null"
  },
  "schedule_items": [
    {
      "scope_item": "string",
      "linked_line_number": 1,
      "estimated_start_date": "YYYY-MM-DD | null",
      "estimated_duration_days": 0,
      "sequence_position": 1,
      "depends_on": [],
      "responsibility": "vendor | contractor | shared",
      "deliverables": [],
      "trigger": "string | null"
    }
  ],
  "accepted_signature_present": false,
  "accepted_signature_name": "string | null",
  "accepted_signature_date": "YYYY-MM-DD | null",
  "job_address": "string | null",
  "confidence_score": 0.0,
  "confidence_details": {},
  "flags": []
}

Numeric fields shown as 0 above accept null where the schema description says "Null if not stated" — emit literal null (not 0, not "null"). Other numeric fields are required (line_items[].amount, line_items[].line_number, total_amount).

The arrays additional_fee_schedule, payment_schedule, schedule_items, and the object payment_terms are all top-level NULL when the proposal does not include those structures. Do NOT emit empty arrays or all-null objects when the proposal is silent — emit literal null at the top level. accepted_signature_present is the only boolean — default false when no signature block exists or block is blank.`;

// ─────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────

function stripCodeFences(text: string): string {
  return text.replace(/```json\s*/gi, "").replace(/```\s*/g, "").trim();
}

function toBuffer(input: Buffer | ArrayBuffer): Buffer {
  if (Buffer.isBuffer(input)) return input;
  return Buffer.from(input);
}

/**
 * Convert a dollar amount (number) to integer cents. Returns null when
 * the input is null/undefined/non-numeric. Uses Math.round to avoid
 * floating-point drift from `42.10 * 100 === 4209.999...`.
 *
 * Negative dollars permitted (credit memos / deductions). NaN/Infinity
 * coerce to null so downstream INSERTs don't blow up the BIGINT bound.
 */
export function dollarsToCents(value: unknown): number | null {
  if (value === null || value === undefined) return null;
  const n = typeof value === "number" ? value : Number(value);
  if (!Number.isFinite(n)) return null;
  return Math.round(n * 100);
}

/**
 * Same as dollarsToCents but throws when null/non-numeric — used for
 * required fields (line item amount, total) where we cannot fall through.
 */
function requireDollarsToCents(value: unknown, fieldName: string): number {
  const cents = dollarsToCents(value);
  if (cents === null) {
    throw new Error(`extractProposal: required field ${fieldName} is null or non-numeric (got ${JSON.stringify(value)})`);
  }
  return cents;
}

function clamp01(n: unknown): number {
  if (typeof n !== "number" || !Number.isFinite(n)) return 0;
  return Math.max(0, Math.min(1, n));
}

function asStringOrNull(v: unknown): string | null {
  if (typeof v === "string" && v.length > 0) return v;
  return null;
}

function asIntOrNull(v: unknown): number | null {
  if (typeof v !== "number" || !Number.isFinite(v)) return null;
  return Math.round(v);
}

function asNumberOrNull(v: unknown): number | null {
  if (typeof v !== "number" || !Number.isFinite(v)) return null;
  return v;
}

function asAttributes(v: unknown): Record<string, unknown> {
  if (v && typeof v === "object" && !Array.isArray(v)) {
    return v as Record<string, unknown>;
  }
  return {};
}

// ─────────────────────────────────────────────────────────────────
// normalizeProposal — pure transform (no I/O), tested directly
// ─────────────────────────────────────────────────────────────────

type RawLineItem = {
  line_number?: unknown;
  description?: unknown;
  description_normalized?: unknown;
  quantity?: unknown;
  unit_of_measure?: unknown;
  unit_price?: unknown;
  amount?: unknown;
  cost_code_suggestion?: unknown;
  material_cost?: unknown;
  labor_cost?: unknown;
  subcontract_cost?: unknown;
  tax?: unknown;
  delivery?: unknown;
  notes_amount?: unknown;
  attributes?: unknown;
};

type RawFeeScheduleEntry = {
  rate_type?: unknown;
  description?: unknown;
  rate?: unknown;
  unit?: unknown;
};

type RawPaymentScheduleEntry = {
  milestone?: unknown;
  percentage_pct?: unknown;
  amount?: unknown;
  trigger?: unknown;
};

type RawPaymentTerms = {
  net_days?: unknown;
  late_interest_rate_pct?: unknown;
  governing_law?: unknown;
  other_terms_text?: unknown;
};

type RawScheduleItem = {
  scope_item?: unknown;
  linked_line_number?: unknown;
  estimated_start_date?: unknown;
  estimated_duration_days?: unknown;
  sequence_position?: unknown;
  depends_on?: unknown;
  responsibility?: unknown;
  deliverables?: unknown;
  trigger?: unknown;
};

type RawProposal = {
  vendor_name?: unknown;
  vendor_address?: unknown;
  proposal_number?: unknown;
  proposal_date?: unknown;
  valid_through?: unknown;
  title?: unknown;
  total_amount?: unknown;
  scope_summary?: unknown;
  inclusions?: unknown;
  exclusions?: unknown;
  notes?: unknown;
  vendor_stated_start_date?: unknown;
  vendor_stated_duration_days?: unknown;
  line_items?: unknown;
  additional_fee_schedule?: unknown;
  payment_schedule?: unknown;
  payment_terms?: unknown;
  schedule_items?: unknown;
  accepted_signature_present?: unknown;
  accepted_signature_name?: unknown;
  accepted_signature_date?: unknown;
  job_address?: unknown;
  confidence_score?: unknown;
  confidence_details?: unknown;
  flags?: unknown;
};

/**
 * Normalize an additional_fee_schedule array. Returns null when the AI
 * emitted null (proposal had no fee table), or filters out invalid
 * entries from any array. Entries with a non-string rate_type are
 * dropped — that's the load-bearing identifier.
 */
function normalizeFeeSchedule(
  v: unknown
): ParsedProposalFeeScheduleEntry[] | null {
  if (v === null || v === undefined) return null;
  if (!Array.isArray(v)) return null;
  const out: ParsedProposalFeeScheduleEntry[] = [];
  for (const e of v as RawFeeScheduleEntry[]) {
    if (!e || typeof e !== "object") continue;
    if (typeof e.rate_type !== "string" || e.rate_type.length === 0) continue;
    out.push({
      rate_type: e.rate_type,
      description: asStringOrNull(e.description),
      rate_cents: dollarsToCents(e.rate),
      unit: asStringOrNull(e.unit),
    });
  }
  // If the array existed but every entry was invalid, return null
  // rather than [] so downstream code can render "no fee schedule"
  // consistently with the no-array case.
  return out.length > 0 ? out : null;
}

/**
 * Normalize a payment_schedule array. Same null/empty behavior as
 * normalizeFeeSchedule. Entries with a non-string milestone are dropped.
 */
function normalizePaymentSchedule(
  v: unknown
): ParsedProposalPaymentScheduleEntry[] | null {
  if (v === null || v === undefined) return null;
  if (!Array.isArray(v)) return null;
  const out: ParsedProposalPaymentScheduleEntry[] = [];
  for (const e of v as RawPaymentScheduleEntry[]) {
    if (!e || typeof e !== "object") continue;
    if (typeof e.milestone !== "string" || e.milestone.length === 0) continue;
    out.push({
      milestone: e.milestone,
      percentage_pct: asNumberOrNull(e.percentage_pct),
      amount_cents: dollarsToCents(e.amount),
      trigger: asStringOrNull(e.trigger),
    });
  }
  return out.length > 0 ? out : null;
}

/**
 * Normalize a schedule_items array. Returns null when the AI emitted
 * null OR every entry was invalid. Entries with a non-string scope_item
 * are dropped. depends_on is filtered to integers only; deliverables
 * to strings only.
 */
function normalizeScheduleItems(
  v: unknown
): ParsedProposalScheduleItem[] | null {
  if (v === null || v === undefined) return null;
  if (!Array.isArray(v)) return null;
  const out: ParsedProposalScheduleItem[] = [];
  for (const e of v as RawScheduleItem[]) {
    if (!e || typeof e !== "object") continue;
    if (typeof e.scope_item !== "string" || e.scope_item.length === 0) continue;
    const depends_on = Array.isArray(e.depends_on)
      ? (e.depends_on as unknown[])
          .map((n) => (typeof n === "number" && Number.isFinite(n) ? Math.round(n) : null))
          .filter((n): n is number => n !== null)
      : [];
    const deliverables = Array.isArray(e.deliverables)
      ? (e.deliverables as unknown[]).filter(
          (s): s is string => typeof s === "string" && s.length > 0
        )
      : [];
    out.push({
      scope_item: e.scope_item,
      linked_line_number: asIntOrNull(e.linked_line_number),
      estimated_start_date: asStringOrNull(e.estimated_start_date),
      estimated_duration_days: asIntOrNull(e.estimated_duration_days),
      sequence_position: asIntOrNull(e.sequence_position),
      depends_on,
      responsibility: asStringOrNull(e.responsibility),
      deliverables,
      trigger: asStringOrNull(e.trigger),
    });
  }
  return out.length > 0 ? out : null;
}

/**
 * Normalize the payment_terms object. Returns null when the AI emitted
 * null OR when every sub-field is null after coercion (a defensively
 * empty object is treated the same as no terms — matches the prompt
 * rule "don't return an object with all-null sub-fields").
 */
function normalizePaymentTerms(
  v: unknown
): ParsedProposalPaymentTerms | null {
  if (v === null || v === undefined) return null;
  if (typeof v !== "object" || Array.isArray(v)) return null;
  const r = v as RawPaymentTerms;
  const net_days = asIntOrNull(r.net_days);
  const late_interest_rate_pct = asNumberOrNull(r.late_interest_rate_pct);
  const governing_law = asStringOrNull(r.governing_law);
  const other_terms_text = asStringOrNull(r.other_terms_text);
  if (
    net_days === null &&
    late_interest_rate_pct === null &&
    governing_law === null &&
    other_terms_text === null
  ) {
    return null;
  }
  return { net_days, late_interest_rate_pct, governing_law, other_terms_text };
}

/**
 * Convert the AI's dollars-shape payload into the cents-shape ParsedProposal.
 * Throws on missing required fields (vendor_name, title, total_amount, per-line
 * description + amount) — these are not recoverable; the prompt is at fault.
 *
 * Exported so the eval (Step 6B) can re-run normalization against captured
 * raw responses without re-paying for AI calls.
 */
export function normalizeProposal(raw: RawProposal): ParsedProposal {
  if (typeof raw.vendor_name !== "string" || raw.vendor_name.length === 0) {
    throw new Error("extractProposal: vendor_name is missing or empty");
  }
  if (typeof raw.title !== "string" || raw.title.length === 0) {
    throw new Error("extractProposal: title is missing or empty");
  }
  if (typeof raw.scope_summary !== "string") {
    throw new Error("extractProposal: scope_summary is missing or non-string");
  }

  const totalCents = requireDollarsToCents(raw.total_amount, "total_amount");

  const rawLines = Array.isArray(raw.line_items) ? (raw.line_items as RawLineItem[]) : [];
  const line_items: ParsedProposalLineItem[] = rawLines.map((rl, idx) => {
    if (typeof rl.description !== "string" || rl.description.length === 0) {
      throw new Error(
        `extractProposal: line_items[${idx}].description is missing or empty`
      );
    }
    const lineNumber =
      typeof rl.line_number === "number" && Number.isFinite(rl.line_number)
        ? Math.round(rl.line_number)
        : idx + 1;
    return {
      line_number: lineNumber,
      description: rl.description,
      description_normalized: asStringOrNull(rl.description_normalized),
      quantity: asNumberOrNull(rl.quantity),
      unit_of_measure: asStringOrNull(rl.unit_of_measure),
      unit_price_cents: dollarsToCents(rl.unit_price),
      total_price_cents: requireDollarsToCents(rl.amount, `line_items[${idx}].amount`),
      cost_code_suggestion: asStringOrNull(rl.cost_code_suggestion),
      material_cost_cents: dollarsToCents(rl.material_cost),
      labor_cost_cents: dollarsToCents(rl.labor_cost),
      subcontract_cost_cents: dollarsToCents(rl.subcontract_cost),
      tax_cents: dollarsToCents(rl.tax),
      delivery_cents: dollarsToCents(rl.delivery),
      notes_cents: dollarsToCents(rl.notes_amount),
      attributes: asAttributes(rl.attributes),
    };
  });

  const confidenceDetails =
    raw.confidence_details &&
    typeof raw.confidence_details === "object" &&
    !Array.isArray(raw.confidence_details)
      ? (raw.confidence_details as Record<string, unknown>)
      : {};
  const cleanedConfidenceDetails: Record<string, number> = {};
  for (const [k, v] of Object.entries(confidenceDetails)) {
    if (typeof v === "number" && Number.isFinite(v)) {
      cleanedConfidenceDetails[k] = clamp01(v);
    }
  }

  const flagsArr = Array.isArray(raw.flags) ? raw.flags : [];
  const flags: string[] = flagsArr.filter((s): s is string => typeof s === "string");

  return {
    vendor_name: raw.vendor_name,
    vendor_address: asStringOrNull(raw.vendor_address),
    proposal_number: asStringOrNull(raw.proposal_number),
    proposal_date: asStringOrNull(raw.proposal_date),
    valid_through: asStringOrNull(raw.valid_through),
    title: raw.title,
    total_cents: totalCents,
    scope_summary: raw.scope_summary,
    inclusions: asStringOrNull(raw.inclusions),
    exclusions: asStringOrNull(raw.exclusions),
    notes: asStringOrNull(raw.notes),
    vendor_stated_start_date: asStringOrNull(raw.vendor_stated_start_date),
    vendor_stated_duration_days: asIntOrNull(raw.vendor_stated_duration_days),
    line_items,
    additional_fee_schedule: normalizeFeeSchedule(raw.additional_fee_schedule),
    payment_schedule: normalizePaymentSchedule(raw.payment_schedule),
    payment_terms: normalizePaymentTerms(raw.payment_terms),
    schedule_items: normalizeScheduleItems(raw.schedule_items),
    accepted_signature_present:
      typeof raw.accepted_signature_present === "boolean"
        ? raw.accepted_signature_present
        : false,
    accepted_signature_name: asStringOrNull(raw.accepted_signature_name),
    accepted_signature_date: asStringOrNull(raw.accepted_signature_date),
    job_address: asStringOrNull(raw.job_address),
    confidence_score: clamp01(raw.confidence_score),
    confidence_details: cleanedConfidenceDetails,
    flags,
    raw_response: raw,
  };
}

// ─────────────────────────────────────────────────────────────────
// extractProposal — public entry point
// ─────────────────────────────────────────────────────────────────

export async function extractProposal(
  input: ExtractProposalInput,
  meta: ExtractProposalMeta
): Promise<ParsedProposal> {
  const base64 = toBuffer(input.pdfBuffer).toString("base64");

  const systemBlocks: Anthropic.Messages.TextBlockParam[] = [
    {
      type: "text",
      text: PROPOSAL_EXTRACT_SYSTEM_PROMPT,
      cache_control: { type: "ephemeral" },
    },
  ];

  const userContent: Anthropic.Messages.ContentBlockParam[] = [
    {
      type: "document",
      source: {
        type: "base64",
        media_type: "application/pdf",
        data: base64,
      },
    },
    {
      type: "text",
      text: "Extract the attached construction proposal. Return only the JSON object.",
    },
  ];

  const response = await callClaude({
    model: "claude-sonnet-4-20250514",
    max_tokens: 4096,
    system: systemBlocks,
    messages: [{ role: "user", content: userContent }],
    function_type: "proposal_extract",
    org_id: meta.org_id,
    user_id: meta.user_id ?? null,
    metadata: { ...meta.metadata, document_id: input.documentId },
  });

  const textBlock = response.content.find((block) => block.type === "text");
  if (!textBlock || textBlock.type !== "text") {
    throw new Error("Proposal extractor returned no text content block");
  }

  const cleaned = stripCodeFences(textBlock.text);
  let parsed: RawProposal;
  try {
    parsed = JSON.parse(cleaned) as RawProposal;
  } catch (err) {
    const msg = err instanceof Error ? err.message : "unknown";
    throw new Error(
      `Proposal extractor returned invalid JSON: ${msg}. First 200 chars: ${cleaned.slice(0, 200)}`
    );
  }

  return normalizeProposal(parsed);
}
