// Sanitized Caldwell fixture — generated by scripts/sanitize-drummond.ts
// Source: pay-app-5-caldwell.pdf cover sheet PCCO log
// Generated: 2026-05-04
// Substitutions applied per .planning/fixtures/drummond/SUBSTITUTION-MAP.md (gitignored)
//
// DO NOT HAND-EDIT. Re-run `npx tsx scripts/sanitize-drummond.ts` to regenerate.

import type { CaldwellChangeOrder } from "./types";

export const CALDWELL_CHANGE_ORDERS: CaldwellChangeOrder[] = [
  {
    "id": "co-caldwell-01",
    "job_id": "j-caldwell-1",
    "pcco_number": 1,
    "description": "Plumbing fixture additions — primary residence (1 shower valve w/single head location, 3 diverters and hand wands). Required CO due to owner specification change after framing inspection. Vendor: Anchor Bay Plumbing Inc.",
    "amount": 389500,
    "gc_fee_amount": 70110,
    "gc_fee_rate": 0.18,
    "total_with_fee": 459610,
    "estimated_days_added": 2,
    "status": "approved",
    "approved_date": "2025-11-15",
    "draw_number": 5
  },
  {
    "id": "co-caldwell-02",
    "job_id": "j-caldwell-1",
    "pcco_number": 2,
    "description": "Electrical field changes — phase 1 (additional outlets in great room, kitchen island, primary suite). Required CO due to owner walkthrough request. Vendor: Coastal Smart Systems LLC. Billed in partial completions across multiple invoices.",
    "amount": 580000,
    "gc_fee_amount": 116000,
    "gc_fee_rate": 0.2,
    "total_with_fee": 696000,
    "estimated_days_added": 0,
    "status": "approved",
    "approved_date": "2025-12-01",
    "draw_number": 5
  },
  {
    "id": "co-caldwell-03",
    "job_id": "j-caldwell-1",
    "pcco_number": 3,
    "description": "Electrical field changes — phase 2 (low-voltage rough-in adjustments for media wall and exterior soffit lighting). Vendor: Coastal Smart Systems LLC. Billed in partial completions.",
    "amount": 120000,
    "gc_fee_amount": 24000,
    "gc_fee_rate": 0.2,
    "total_with_fee": 144000,
    "estimated_days_added": 0,
    "status": "approved",
    "approved_date": "2025-12-15",
    "draw_number": 5
  },
  {
    "id": "co-caldwell-04",
    "job_id": "j-caldwell-1",
    "pcco_number": 4,
    "description": "[SYNTHESIZED per nwrp38] Framing scope reduction — DEDUCTIVE. Owner-directed deletion of bonus room over garage (truss layout redesigned 2025-11-01; existing roof line carried as gable instead of bonus-room dormer). Net deduct: framing labor + materials for 320 sf bonus room scope. Vendor: Bay Region Carpentry Inc.",
    "amount": -850000,
    "gc_fee_amount": -170000,
    "gc_fee_rate": 0.2,
    "total_with_fee": -1020000,
    "estimated_days_added": -3,
    "status": "approved",
    "approved_date": "2025-11-08",
    "draw_number": 5
  },
  {
    "id": "co-caldwell-05",
    "job_id": "j-caldwell-1",
    "pcco_number": 5,
    "description": "[SYNTHESIZED per nwrp38] Drywall allowance reconciliation — ALLOWANCE_RECON. Original budget allowance $48,000; actual scope (Level 5 finish in primary suite + great room ceiling, Level 4 elsewhere) finalized at $52,400 after owner walkthrough. Net add to reflect true scope. Vendor: Sandhill Drywall Inc.",
    "amount": 440000,
    "gc_fee_amount": 79200,
    "gc_fee_rate": 0.18,
    "total_with_fee": 519200,
    "estimated_days_added": 0,
    "status": "approved",
    "approved_date": "2025-12-10",
    "draw_number": 5
  }
];
