// Sanitized Caldwell fixture — generated by scripts/sanitize-drummond.ts
// Source: Reference cost-codes PDF + standard 5-digit AIA codes
// Generated: 2026-05-04
// Substitutions applied per .planning/fixtures/drummond/SUBSTITUTION-MAP.md (gitignored)
//
// DO NOT HAND-EDIT. Re-run `npx tsx scripts/sanitize-drummond.ts` to regenerate.

import type { CaldwellCostCode } from "./types";

export const CALDWELL_COST_CODES: CaldwellCostCode[] = [
  {
    "id": "cc-01101",
    "code": "01101",
    "description": "Architectural Services",
    "category": "Pre-construction",
    "sort_order": 1
  },
  {
    "id": "cc-01104",
    "code": "01104",
    "description": "Pre-Permitting Planning Services",
    "category": "Pre-construction",
    "sort_order": 2
  },
  {
    "id": "cc-01201",
    "code": "01201",
    "description": "Engineering — Structural",
    "category": "Pre-construction",
    "sort_order": 3
  },
  {
    "id": "cc-01301",
    "code": "01301",
    "description": "Survey & Permitting Fees",
    "category": "Pre-construction",
    "sort_order": 4
  },
  {
    "id": "cc-03110",
    "code": "03110",
    "description": "Temporary Electric & Water",
    "category": "Site logistics",
    "sort_order": 5
  },
  {
    "id": "cc-03112",
    "code": "03112",
    "description": "Debris Removal",
    "category": "Site logistics",
    "sort_order": 6
  },
  {
    "id": "cc-03115",
    "code": "03115",
    "description": "Site Protection & Fencing",
    "category": "Site logistics",
    "sort_order": 7
  },
  {
    "id": "cc-04101",
    "code": "04101",
    "description": "Site Work — Clearing & Grading",
    "category": "Site work",
    "sort_order": 8
  },
  {
    "id": "cc-04201",
    "code": "04201",
    "description": "Site Work — Driveway & Hardscape",
    "category": "Site work",
    "sort_order": 9
  },
  {
    "id": "cc-05101",
    "code": "05101",
    "description": "Concrete / Foundation",
    "category": "Concrete",
    "sort_order": 10
  },
  {
    "id": "cc-05201",
    "code": "05201",
    "description": "Concrete / Slab on Grade",
    "category": "Concrete",
    "sort_order": 11
  },
  {
    "id": "cc-06101",
    "code": "06101",
    "description": "Framing — Rough Carpentry",
    "category": "Framing",
    "sort_order": 12
  },
  {
    "id": "cc-06201",
    "code": "06201",
    "description": "Framing — Trusses",
    "category": "Framing",
    "sort_order": 13
  },
  {
    "id": "cc-07101",
    "code": "07101",
    "description": "Roofing — Underlayment & Shingles",
    "category": "Roofing",
    "sort_order": 14
  },
  {
    "id": "cc-07201",
    "code": "07201",
    "description": "Roofing — Metal & Standing Seam",
    "category": "Roofing",
    "sort_order": 15
  },
  {
    "id": "cc-08101",
    "code": "08101",
    "description": "Insulation — Spray Foam",
    "category": "Envelope",
    "sort_order": 16
  },
  {
    "id": "cc-09101",
    "code": "09101",
    "description": "Electrical — Rough",
    "category": "Electrical",
    "sort_order": 17
  },
  {
    "id": "cc-09201",
    "code": "09201",
    "description": "Electrical — Trim & Finish",
    "category": "Electrical",
    "sort_order": 18
  },
  {
    "id": "cc-10101",
    "code": "10101",
    "description": "Plumbing — Rough",
    "category": "Plumbing",
    "sort_order": 19
  },
  {
    "id": "cc-10201",
    "code": "10201",
    "description": "Plumbing — Trim & Fixtures",
    "category": "Plumbing",
    "sort_order": 20
  },
  {
    "id": "cc-12101",
    "code": "12101",
    "description": "HVAC — Rough & Equipment",
    "category": "HVAC",
    "sort_order": 21
  },
  {
    "id": "cc-13101",
    "code": "13101",
    "description": "Smart Home — Low Voltage & Security",
    "category": "Systems",
    "sort_order": 22
  },
  {
    "id": "cc-14101",
    "code": "14101",
    "description": "Doors & Windows — Exterior",
    "category": "Openings",
    "sort_order": 23
  },
  {
    "id": "cc-14201",
    "code": "14201",
    "description": "Garage Doors",
    "category": "Openings",
    "sort_order": 24
  },
  {
    "id": "cc-15101",
    "code": "15101",
    "description": "Drywall — Hang & Finish",
    "category": "Finishes",
    "sort_order": 25
  },
  {
    "id": "cc-15201",
    "code": "15201",
    "description": "Tile — Floor & Wall",
    "category": "Finishes",
    "sort_order": 26
  },
  {
    "id": "cc-15301",
    "code": "15301",
    "description": "Trim & Millwork",
    "category": "Finishes",
    "sort_order": 27
  },
  {
    "id": "cc-15401",
    "code": "15401",
    "description": "Cabinetry & Built-ins",
    "category": "Finishes",
    "sort_order": 28
  },
  {
    "id": "cc-15501",
    "code": "15501",
    "description": "Painting & Coatings",
    "category": "Finishes",
    "sort_order": 29
  },
  {
    "id": "cc-16101",
    "code": "16101",
    "description": "Lumber & Building Materials",
    "category": "Materials",
    "sort_order": 30
  }
];
