// Sanitized Caldwell fixture — generated by scripts/sanitize-drummond.ts
// Source: pay-app-1-caldwell-2025-jul.xlsx through pay-app-5-caldwell.pdf
// Generated: 2026-05-04
// Substitutions applied per .planning/fixtures/drummond/SUBSTITUTION-MAP.md (gitignored)
//
// DO NOT HAND-EDIT. Re-run `npx tsx scripts/sanitize-drummond.ts` to regenerate.

import type { CaldwellDraw } from "./types";

export const CALDWELL_DRAWS: CaldwellDraw[] = [
  {
    "id": "d-caldwell-01",
    "job_id": "j-caldwell-1",
    "draw_number": 1,
    "application_date": "2025-08-05",
    "period_start": "2025-03-01",
    "period_end": "2025-07-31",
    "status": "paid",
    "revision_number": 0,
    "original_contract_sum": 287500000,
    "net_change_orders": 8750000,
    "contract_sum_to_date": 296250000,
    "total_completed_to_date": 86250000,
    "less_previous_payments": 0,
    "current_payment_due": 86250000,
    "balance_to_finish": 210000000,
    "deposit_amount": 28750000,
    "submitted_at": "2025-08-05T14:30:00Z",
    "paid_at": "2025-07-31T11:15:00Z"
  },
  {
    "id": "d-caldwell-02",
    "job_id": "j-caldwell-1",
    "draw_number": 2,
    "application_date": "2025-09-05",
    "period_start": "2025-08-01",
    "period_end": "2025-08-31",
    "status": "paid",
    "revision_number": 0,
    "original_contract_sum": 287500000,
    "net_change_orders": 8750000,
    "contract_sum_to_date": 296250000,
    "total_completed_to_date": 130500000,
    "less_previous_payments": 86250000,
    "current_payment_due": 44250000,
    "balance_to_finish": 165750000,
    "deposit_amount": 28750000,
    "submitted_at": "2025-09-05T14:30:00Z",
    "paid_at": "2025-08-31T11:15:00Z"
  },
  {
    "id": "d-caldwell-03",
    "job_id": "j-caldwell-1",
    "draw_number": 3,
    "application_date": "2025-10-05",
    "period_start": "2025-09-01",
    "period_end": "2025-09-30",
    "status": "paid",
    "revision_number": 0,
    "original_contract_sum": 287500000,
    "net_change_orders": 8750000,
    "contract_sum_to_date": 296250000,
    "total_completed_to_date": 172800000,
    "less_previous_payments": 130500000,
    "current_payment_due": 42300000,
    "balance_to_finish": 123450000,
    "deposit_amount": 28750000,
    "submitted_at": "2025-10-05T14:30:00Z",
    "paid_at": "2025-09-30T11:15:00Z"
  },
  {
    "id": "d-caldwell-04",
    "job_id": "j-caldwell-1",
    "draw_number": 4,
    "application_date": "2025-11-05",
    "period_start": "2025-10-01",
    "period_end": "2025-10-31",
    "status": "paid",
    "revision_number": 0,
    "original_contract_sum": 287500000,
    "net_change_orders": 8750000,
    "contract_sum_to_date": 296250000,
    "total_completed_to_date": 214600000,
    "less_previous_payments": 172800000,
    "current_payment_due": 41800000,
    "balance_to_finish": 81650000,
    "deposit_amount": 28750000,
    "submitted_at": "2025-11-05T14:30:00Z",
    "paid_at": "2025-10-31T11:15:00Z"
  },
  {
    "id": "d-caldwell-05",
    "job_id": "j-caldwell-1",
    "draw_number": 5,
    "application_date": "2025-12-05",
    "period_start": "2025-11-01",
    "period_end": "2025-11-30",
    "status": "submitted",
    "revision_number": 0,
    "original_contract_sum": 287500000,
    "net_change_orders": 8750000,
    "contract_sum_to_date": 296250000,
    "total_completed_to_date": 252100000,
    "less_previous_payments": 214600000,
    "current_payment_due": 37500000,
    "balance_to_finish": 44150000,
    "deposit_amount": 28750000,
    "submitted_at": "2025-12-05T14:30:00Z",
    "paid_at": null
  }
];
