// Sanitized Caldwell fixture — generated by scripts/sanitize-drummond.ts
// Source: drummond-invoice-fields.json (gitignored, sanitized) + invoices-batch-caldwell-2025-11.pdf
// Generated: 2026-05-04
// Substitutions applied per .planning/fixtures/drummond/SUBSTITUTION-MAP.md (gitignored)
//
// DO NOT HAND-EDIT. Re-run `npx tsx scripts/sanitize-drummond.ts` to regenerate.

import type { CaldwellInvoice } from "./types";

export const CALDWELL_INVOICES: CaldwellInvoice[] = [
  {
    "id": "inv-caldwell-001",
    "vendor_id": "v-caldwell-coastal-smart-systems",
    "job_id": "j-caldwell-1",
    "cost_code_id": "cc-09101",
    "po_id": null,
    "co_id": null,
    "invoice_number": "INV-105472",
    "invoice_date": "2025-12-19",
    "description": "Progress billing — electrical change orders (PCCO #2 + PCCO #3 partial completions). Field changes per owner walkthrough.",
    "invoice_type": "progress",
    "total_amount": 284584,
    "confidence_score": 0.95,
    "confidence_details": {
      "vendor_name": 0.97,
      "invoice_number": 0.99,
      "total_amount": 0.99,
      "job_reference": 0.92,
      "cost_code_suggestion": 0.78
    },
    "status": "paid",
    "received_date": "2025-12-19",
    "payment_date": "2025-12-30",
    "draw_id": "d-caldwell-05",
    "line_items": [
      {
        "description": "Progress billing - Electrical / Change Order #2 - partial completion (additional outlets)",
        "date": null,
        "qty": 1,
        "unit": "ea",
        "rate": 2579.17,
        "amount": 257917
      },
      {
        "description": "Progress billing - Electrical / Change Order #3 - partial completion (low-voltage rough-in)",
        "date": null,
        "qty": 1,
        "unit": "ea",
        "rate": 266.67,
        "amount": 26667
      }
    ],
    "flags": [
      "change_order_referenced",
      "multi_co_span",
      "field_changes_note"
    ],
    "original_file_url": null
  },
  {
    "id": "inv-caldwell-002",
    "vendor_id": "v-caldwell-anchor-bay-plumbing",
    "job_id": "j-caldwell-1",
    "cost_code_id": "cc-10101",
    "po_id": null,
    "co_id": null,
    "invoice_number": "26125163",
    "invoice_date": "2025-10-23",
    "description": "Plumbing rough-in (Rough 2) — primary residence (12 fixtures including kitchen sink, pot filler, ice maker box, utility/bar sink, washer box, 3 bathroom sinks, 3 WCs, 2 showers, diverter/hand wand, tub/shower, 5 hose bibs, outdoor shower) + future ground floor half bath/kitchen + PCCO #1 (1 shower valve + 3 diverters/hand wands). Supply lines: Uponor PEX. Sanitary lines: PVC.",
    "invoice_type": "progress",
    "total_amount": 1989900,
    "confidence_score": 0.91,
    "confidence_details": {
      "vendor_name": 0.96,
      "invoice_number": 0.98,
      "total_amount": 0.99,
      "job_reference": 0.85,
      "cost_code_suggestion": 0.72
    },
    "status": "in_draw",
    "received_date": "2025-10-24",
    "payment_date": "2025-11-17",
    "draw_id": "d-caldwell-05",
    "line_items": [
      {
        "description": "Rough 2: Rough-in waste & water — primary residence (12 fixtures)",
        "date": "2025-10-23",
        "qty": 1,
        "unit": "lump",
        "rate": 13676,
        "amount": 1367600
      },
      {
        "description": "Rough 2: Rough-in waste & water — future ground floor half bath/kitchen",
        "date": "2025-10-23",
        "qty": 1,
        "unit": "lump",
        "rate": 2328,
        "amount": 232800
      },
      {
        "description": "Change Order #1: Rough-in waste & water — added fixtures (1 shower valve w/single head location, 3 diverters and hand wands)",
        "date": "2025-10-23",
        "qty": 1,
        "unit": "lump",
        "rate": 3895,
        "amount": 389500
      }
    ],
    "flags": [
      "change_order_referenced",
      "daily_log_entries_present",
      "fixture_count_high"
    ],
    "original_file_url": null
  },
  {
    "id": "inv-caldwell-003",
    "vendor_id": "v-caldwell-coastline-foam",
    "job_id": "j-caldwell-1",
    "cost_code_id": "cc-07101",
    "po_id": null,
    "co_id": null,
    "invoice_number": "5977",
    "invoice_date": "2025-12-01",
    "description": "Spray foam insulation — primary residence per PO JXTFQ3363-01. Closed-cell SPF for exterior walls + open-cell for interior partitions. PO balance reconciliation noted.",
    "invoice_type": "lump_sum",
    "total_amount": 1792156,
    "confidence_score": 0.88,
    "confidence_details": {
      "vendor_name": 0.94,
      "invoice_number": 0.92,
      "total_amount": 0.99,
      "job_reference": 0.9,
      "cost_code_suggestion": 0.65
    },
    "status": "qa_review",
    "received_date": "2025-12-02",
    "payment_date": null,
    "draw_id": null,
    "line_items": [
      {
        "description": "Spray foam insulation — per PO JXTFQ3363-01 (lump sum, no detailed line breakdown on vendor invoice)",
        "date": null,
        "qty": 1,
        "unit": "lump",
        "rate": 17921.56,
        "amount": 1792156
      }
    ],
    "flags": [
      "lump_sum_no_line_items",
      "po_balance_close",
      "po_reference_present"
    ],
    "original_file_url": null
  },
  {
    "id": "inv-caldwell-004",
    "vendor_id": "v-caldwell-ferguson",
    "job_id": "j-caldwell-1",
    "cost_code_id": "cc-10101",
    "po_id": null,
    "co_id": null,
    "invoice_number": "6713881",
    "invoice_date": "2025-10-22",
    "description": "Plumbing fixtures supply — Bellwedge 66x32 bathtub w/LH drain (white) + 30in PVC cable bath drain w/tube + cable bath drain trim. Manatee County sales tax included.",
    "invoice_type": "lump_sum",
    "total_amount": 146105,
    "confidence_score": 0.93,
    "confidence_details": {
      "vendor_name": 0.99,
      "invoice_number": 0.99,
      "total_amount": 0.99,
      "job_reference": 0.95,
      "cost_code_suggestion": 0.82
    },
    "status": "pm_approved",
    "received_date": "2025-10-23",
    "payment_date": null,
    "draw_id": null,
    "line_items": [
      {
        "description": "K847-0 / 66x32 Bellwedge bath w/LH drain (white)",
        "date": null,
        "qty": 1,
        "unit": "ea",
        "rate": 1171.59,
        "amount": 117159
      },
      {
        "description": "K37383-NA / 30in PVC cable bath drain w/tube",
        "date": null,
        "qty": 1,
        "unit": "ea",
        "rate": 91.41,
        "amount": 9141
      },
      {
        "description": "KT37391-BN / Cable bath drain trim — basic rough",
        "date": null,
        "qty": 1,
        "unit": "ea",
        "rate": 102.47,
        "amount": 10247
      },
      {
        "description": "Sales tax (Manatee County, 7.0%)",
        "date": null,
        "qty": 1,
        "unit": "tax",
        "rate": 95.58,
        "amount": 9558
      }
    ],
    "flags": [
      "national_supplier",
      "sales_tax_present",
      "no_sub_per_rule_1"
    ],
    "original_file_url": null
  },
  {
    "id": "inv-caldwell-005",
    "vendor_id": "v-caldwell-sun-coast-lumber",
    "job_id": "j-caldwell-1",
    "cost_code_id": "cc-06101",
    "po_id": null,
    "co_id": null,
    "invoice_number": "525830",
    "invoice_date": "2025-11-03",
    "description": "Small framing supplies pickup — bit clip, Diablo framing saw blade, 1/2in CDX plywood (4-ply). Note on stamp: $34.43 supplies portion is non-billable; $25.66 framing material billable to job.",
    "invoice_type": "lump_sum",
    "total_amount": 6009,
    "confidence_score": 0.78,
    "confidence_details": {
      "vendor_name": 0.85,
      "invoice_number": 0.8,
      "total_amount": 0.85,
      "job_reference": 0.62,
      "cost_code_suggestion": 0.65
    },
    "status": "ai_processed",
    "received_date": "2025-11-03",
    "payment_date": null,
    "draw_id": null,
    "line_items": [
      {
        "description": "NIBPI611 / 2in 10pc No.2 PH bit clip",
        "date": null,
        "qty": 1,
        "unit": "ea",
        "rate": 18.99,
        "amount": 1899
      },
      {
        "description": "1817733 / Diablo framing saw blade 6-1/2in",
        "date": null,
        "qty": 1,
        "unit": "ea",
        "rate": 13.19,
        "amount": 1319
      },
      {
        "description": "12CD / 1/2in CDX 4x8 plywood (4-ply)",
        "date": null,
        "qty": 1,
        "unit": "ea",
        "rate": 23.98,
        "amount": 2398
      },
      {
        "description": "Sales tax (Florida State, 7.0%)",
        "date": null,
        "qty": 1,
        "unit": "tax",
        "rate": 3.93,
        "amount": 393
      }
    ],
    "flags": [
      "handwritten_notes_detected",
      "low_amount",
      "sales_tax_present",
      "split_billable_nonbillable",
      "older_pos_system_low_confidence"
    ],
    "original_file_url": null
  },
  {
    "id": "inv-caldwell-006",
    "vendor_id": "v-caldwell-fpl",
    "job_id": "j-caldwell-1",
    "cost_code_id": "cc-03110",
    "po_id": null,
    "co_id": null,
    "invoice_number": null,
    "invoice_date": "2025-11-18",
    "description": "Electric service — temporary construction electric, 28-day billing period (Oct 21 - Nov 18 2025). Service address: 712 Pine Ave # CNST CNST, Anna Maria, FL 34216. Account 50051-12345.",
    "invoice_type": "lump_sum",
    "total_amount": 5813,
    "confidence_score": 0.85,
    "confidence_details": {
      "vendor_name": 0.99,
      "invoice_number": 0,
      "total_amount": 0.99,
      "job_reference": 0.85,
      "cost_code_suggestion": 0.96
    },
    "status": "pm_review",
    "received_date": "2025-11-21",
    "payment_date": null,
    "draw_id": null,
    "line_items": [
      {
        "description": "Electric service — 28 days (Oct 21 - Nov 18 2025), temporary construction service at 712 Pine Ave",
        "date": "2025-11-18",
        "qty": 1,
        "unit": "month",
        "rate": 58.13,
        "amount": 5813
      }
    ],
    "flags": [
      "utility_account",
      "fixed_recurring",
      "no_invoice_number",
      "no_sub_per_rule_1",
      "temp_construction_service"
    ],
    "original_file_url": null
  },
  {
    "id": "inv-caldwell-007",
    "vendor_id": "v-caldwell-bay-region-carpentry",
    "job_id": "j-caldwell-1",
    "cost_code_id": "cc-06101",
    "po_id": null,
    "co_id": null,
    "invoice_number": "TM-2025-1114",
    "invoice_date": "2025-11-14",
    "description": "[SYNTHESIZED per nwrp38] Time and materials — framing labor + skid steer equipment for great room beam install, primary suite ceiling, and stair rough framing. Daily breakdown 5 days (Mon 2025-11-10 → Fri 2025-11-14). Crew: 1 lead carpenter @ $68/hr + 2-3 laborers @ $42/hr ea + skid steer operator + equipment @ $125/hr (variable hours per day).",
    "invoice_type": "time_and_materials",
    "total_amount": 837700,
    "confidence_score": 0.84,
    "confidence_details": {
      "vendor_name": 0.94,
      "invoice_number": 0.88,
      "total_amount": 0.99,
      "job_reference": 0.88,
      "cost_code_suggestion": 0.86
    },
    "status": "pm_review",
    "received_date": "2025-11-17",
    "payment_date": null,
    "draw_id": null,
    "line_items": [
      {
        "description": "Mon 2025-11-10 — Layout + crane prep, headers for great room beam pocket. Crew: 1 lead carp (8h × $68 = $544) + 2 laborers (8h ea × $42 = $672) + skid steer + operator (6h × $125 = $750).",
        "date": "2025-11-10",
        "qty": 1,
        "unit": "day",
        "rate": 1966,
        "amount": 196600
      },
      {
        "description": "Tue 2025-11-11 — Set great room 32ft LVL beam, frame opening for 12ft bifold doors. Crew: 1 lead carp (8h × $68 = $544) + 2 laborers (8h ea × $42 = $672) + skid steer + operator (4h × $125 = $500).",
        "date": "2025-11-11",
        "qty": 1,
        "unit": "day",
        "rate": 1716,
        "amount": 171600
      },
      {
        "description": "Wed 2025-11-12 — Lift LVL beam to second floor, frame stair stringers. Crew: 1 lead carp (8h × $68 = $544) + 3 laborers (8h ea × $42 = $1,008). No equipment day.",
        "date": "2025-11-12",
        "qty": 1,
        "unit": "day",
        "rate": 1552,
        "amount": 155200
      },
      {
        "description": "Thu 2025-11-13 — Frame primary suite ceiling, install collar ties + ridge beam blocking. Crew: 1 lead carp (8h × $68 = $544) + 3 laborers (8h ea × $42 = $1,008) + skid steer + operator (3h × $125 = $375).",
        "date": "2025-11-13",
        "qty": 1,
        "unit": "day",
        "rate": 1927,
        "amount": 192700
      },
      {
        "description": "Fri 2025-11-14 — Punch list framing — closet shelves, soffit blocking, weather wrap repair. Crew: 1 lead carp (8h × $68 = $544) + 2 laborers (8h ea × $42 = $672). No equipment day.",
        "date": "2025-11-14",
        "qty": 1,
        "unit": "day",
        "rate": 1216,
        "amount": 121600
      }
    ],
    "flags": [
      "synthesized",
      "time_and_materials_format",
      "daily_labor_entries",
      "crew_mix_lead_lab_skid",
      "fictional_per_nwrp38_option_b"
    ],
    "original_file_url": null
  }
];
