// Sanitized Caldwell fixture — generated by scripts/sanitize-drummond.ts
// Source: pay-app-5-caldwell.pdf + SUBSTITUTION-MAP
// Generated: 2026-05-04
// Substitutions applied per .planning/fixtures/drummond/SUBSTITUTION-MAP.md (gitignored)
//
// DO NOT HAND-EDIT. Re-run `npx tsx scripts/sanitize-drummond.ts` to regenerate.

import type { CaldwellJob } from "./types";

export const CALDWELL_JOBS: CaldwellJob[] = [
  {
    "id": "j-caldwell-1",
    "name": "Caldwell - 712 Pine Ave",
    "address": "712 Pine Ave, Anna Maria, FL 34216",
    "client_name": "Caldwell",
    "client_email": "client@caldwellresidence.example",
    "client_phone": "(941) 555-0701",
    "contract_type": "cost_plus",
    "original_contract_amount": 425000000,
    "current_contract_amount": 431079100,
    "pm_id": "pm-brent-mullins",
    "status": "active",
    "deposit_percentage": 0.1,
    "gc_fee_percentage": 0.2
  }
];
