// Sanitized Caldwell fixture — generated by scripts/sanitize-drummond.ts
// Source: lien-releases-caldwell-2025-11.pdf
// Generated: 2026-05-04
// Substitutions applied per .planning/fixtures/drummond/SUBSTITUTION-MAP.md (gitignored)
//
// DO NOT HAND-EDIT. Re-run `npx tsx scripts/sanitize-drummond.ts` to regenerate.

import type { CaldwellLienRelease } from "./types";

export const CALDWELL_LIEN_RELEASES: CaldwellLienRelease[] = [
  {
    "id": "lr-caldwell-001",
    "job_id": "j-caldwell-1",
    "vendor_id": "v-caldwell-coastal-smart-systems",
    "invoice_id": "inv-caldwell-001",
    "draw_id": "d-caldwell-05",
    "release_type": "unconditional_progress",
    "status": "received",
    "release_date": "2026-01-05",
    "amount_through": 284584
  },
  {
    "id": "lr-caldwell-002",
    "job_id": "j-caldwell-1",
    "vendor_id": "v-caldwell-anchor-bay-plumbing",
    "invoice_id": "inv-caldwell-002",
    "draw_id": "d-caldwell-05",
    "release_type": "conditional_progress",
    "status": "received",
    "release_date": "2025-11-20",
    "amount_through": 1989900
  },
  {
    "id": "lr-caldwell-003",
    "job_id": "j-caldwell-1",
    "vendor_id": "v-caldwell-coastline-foam",
    "invoice_id": "inv-caldwell-003",
    "draw_id": null,
    "release_type": "conditional_progress",
    "status": "pending",
    "release_date": null,
    "amount_through": 1792156
  }
];
