// Sanitized Caldwell fixture — generated by scripts/sanitize-drummond.ts
// Source: Derived from CALDWELL_INVOICES (status='paid') via Ross Built payment-schedule rule
// Generated: 2026-05-04
// Substitutions applied per .planning/fixtures/drummond/SUBSTITUTION-MAP.md (gitignored)
//
// DO NOT HAND-EDIT. Re-run `npx tsx scripts/sanitize-drummond.ts` to regenerate.

import type { CaldwellPayment } from "./types";

export const CALDWELL_PAYMENTS: CaldwellPayment[] = [
  {
    "id": "p-caldwell-001",
    "invoice_id": "inv-caldwell-001",
    "job_id": "j-caldwell-1",
    "vendor_id": "v-caldwell-coastal-smart-systems",
    "amount": 284584,
    "check_number": "5000",
    "payment_date": "2025-12-30",
    "picked_up": true,
    "picked_up_at": "2025-12-30T15:30:00Z"
  }
];
