// Sanitized Caldwell fixture — generated by scripts/sanitize-drummond.ts
// Source: Derived from invoice/PO/budget drift across 4 candidates × 2 drift types
// Generated: 2026-05-04
// Substitutions applied per .planning/fixtures/drummond/SUBSTITUTION-MAP.md (gitignored)
//
// DO NOT HAND-EDIT. Re-run `npx tsx scripts/sanitize-drummond.ts` to regenerate.

import type { CaldwellReconciliationPair } from "./types";

export const CALDWELL_RECONCILIATION_PAIRS: CaldwellReconciliationPair[] = [
  {
    "id": "rec-caldwell-invoice_po-1",
    "drift_type": "invoice_po",
    "imported": {
      "invoice_id": "inv-caldwell-001",
      "vendor_name": "Anchor Bay Plumbing Inc",
      "po_amount_dollars": 18000,
      "invoice_amount_dollars": 19899
    },
    "current": {
      "invoice_id": "inv-caldwell-001",
      "vendor_name": "Anchor Bay Plumbing Inc",
      "po_amount_dollars": 18000,
      "invoice_amount_dollars": 19899,
      "po_id": null
    },
    "diffs": [
      {
        "field": "po_id",
        "imported_value": "PO-2025-0042",
        "current_value": null
      },
      {
        "field": "amount_overage",
        "imported_value": 1899,
        "current_value": 1899
      }
    ]
  },
  {
    "id": "rec-caldwell-invoice_po-2",
    "drift_type": "invoice_po",
    "imported": {
      "invoice_id": "inv-caldwell-002",
      "vendor_name": "Bay Region Carpentry Inc",
      "po_amount_dollars": 22000,
      "invoice_amount_dollars": 18540
    },
    "current": {
      "invoice_id": "inv-caldwell-002",
      "vendor_name": "Bay Region Carpentry Inc",
      "po_amount_dollars": 22000,
      "invoice_amount_dollars": 18540,
      "po_id": null
    },
    "diffs": [
      {
        "field": "po_id",
        "imported_value": "PO-2025-0048",
        "current_value": null
      },
      {
        "field": "po_remaining_dollars",
        "imported_value": 3460,
        "current_value": 0
      }
    ]
  },
  {
    "id": "rec-caldwell-invoice_po-3",
    "drift_type": "invoice_po",
    "imported": {
      "invoice_id": "inv-caldwell-003",
      "vendor_name": "Sandhill Drywall Inc",
      "po_amount_dollars": 41250,
      "invoice_amount_dollars": 41250
    },
    "current": {
      "invoice_id": "inv-caldwell-003",
      "vendor_name": "Sandhill Drywall Inc",
      "po_amount_dollars": null,
      "invoice_amount_dollars": 41250,
      "po_id": null
    },
    "diffs": [
      {
        "field": "po_amount_dollars",
        "imported_value": 41250,
        "current_value": null
      },
      {
        "field": "po_id",
        "imported_value": "PO-2025-0061",
        "current_value": null
      }
    ]
  },
  {
    "id": "rec-caldwell-invoice_po-4",
    "drift_type": "invoice_po",
    "imported": {
      "invoice_id": "inv-caldwell-006",
      "vendor_name": "Coastline Foam LLC",
      "po_amount_dollars": 17000,
      "invoice_amount_dollars": 17921.56
    },
    "current": {
      "invoice_id": "inv-caldwell-006",
      "vendor_name": "Coastline Foam LLC",
      "po_amount_dollars": 17000,
      "invoice_amount_dollars": 17921.56,
      "po_id": "PO-CALDWELL-0034"
    },
    "diffs": [
      {
        "field": "amount_overage_dollars",
        "imported_value": 921.56,
        "current_value": 921.56
      },
      {
        "field": "po_status",
        "imported_value": "fully_invoiced",
        "current_value": "fully_invoiced"
      }
    ]
  },
  {
    "id": "rec-caldwell-draw_budget-1",
    "drift_type": "draw_budget",
    "imported": {
      "cost_code": "06101",
      "budget_revised_dollars": 29625,
      "draw_total_to_date_dollars": 25210,
      "percent_complete": 0.851
    },
    "current": {
      "cost_code": "06101",
      "budget_revised_dollars": 29625,
      "draw_total_to_date_dollars": 25210,
      "percent_complete": 0.851
    },
    "diffs": [
      {
        "field": "co_attribution",
        "imported_value": "co-caldwell-01",
        "current_value": null
      },
      {
        "field": "co_amount_dollars",
        "imported_value": 35000,
        "current_value": 0
      }
    ]
  },
  {
    "id": "rec-caldwell-draw_budget-2",
    "drift_type": "draw_budget",
    "imported": {
      "cost_code": "12101",
      "budget_revised_dollars": 14812.5,
      "draw_total_to_date_dollars": 10368.62,
      "percent_complete": 0.7
    },
    "current": {
      "cost_code": "12101",
      "budget_revised_dollars": 14375,
      "draw_total_to_date_dollars": 10368.62,
      "percent_complete": 0.721
    },
    "diffs": [
      {
        "field": "budget_revised_dollars",
        "imported_value": 14812.5,
        "current_value": 14375
      },
      {
        "field": "co_attribution",
        "imported_value": "co-caldwell-03",
        "current_value": null
      }
    ]
  },
  {
    "id": "rec-caldwell-draw_budget-3",
    "drift_type": "draw_budget",
    "imported": {
      "cost_code": "15101",
      "budget_revised_dollars": 14812.5,
      "draw_total_to_date_dollars": 12605,
      "percent_complete": 0.851
    },
    "current": {
      "cost_code": "15101",
      "budget_revised_dollars": 14812.5,
      "draw_total_to_date_dollars": 0,
      "percent_complete": 0
    },
    "diffs": [
      {
        "field": "draw_total_to_date_dollars",
        "imported_value": 12605,
        "current_value": 0
      },
      {
        "field": "draw_id",
        "imported_value": "d-caldwell-05",
        "current_value": null
      }
    ]
  },
  {
    "id": "rec-caldwell-draw_budget-4",
    "drift_type": "draw_budget",
    "imported": {
      "cost_code": "13101",
      "budget_revised_dollars": 5925,
      "draw_total_to_date_dollars": 2845.84,
      "percent_complete": 0.48
    },
    "current": {
      "cost_code": "13101",
      "budget_revised_dollars": 5925,
      "draw_total_to_date_dollars": 2845.84,
      "percent_complete": 0.48
    },
    "diffs": [
      {
        "field": "vendor_id",
        "imported_value": "v-caldwell-coastal-smart-systems",
        "current_value": "v-caldwell-coastal-smart-systems"
      },
      {
        "field": "lien_release_id",
        "imported_value": "lr-caldwell-001",
        "current_value": null
      }
    ]
  }
];
