// Sanitized Caldwell fixture — generated by scripts/sanitize-drummond.ts
// Source: schedule-caldwell-712-pine-ave.xlsx
// Generated: 2026-05-04
// Substitutions applied per .planning/fixtures/drummond/SUBSTITUTION-MAP.md (gitignored)
//
// DO NOT HAND-EDIT. Re-run `npx tsx scripts/sanitize-drummond.ts` to regenerate.

import type { CaldwellScheduleItem } from "./types";

export const CALDWELL_SCHEDULE_ITEMS: CaldwellScheduleItem[] = [
  {
    "id": "s-caldwell-001",
    "job_id": "j-caldwell-1",
    "name": "Architectural Services — Schematic + DD",
    "start_date": "2025-01-15",
    "end_date": "2025-02-28",
    "predecessor_ids": [],
    "percent_complete": 1,
    "status": "complete",
    "is_milestone": false
  },
  {
    "id": "s-caldwell-002",
    "job_id": "j-caldwell-1",
    "name": "Permits — County + Stormwater",
    "start_date": "2025-02-15",
    "end_date": "2025-03-15",
    "predecessor_ids": [
      "s-caldwell-001"
    ],
    "percent_complete": 1,
    "status": "complete",
    "is_milestone": false
  },
  {
    "id": "s-caldwell-003",
    "job_id": "j-caldwell-1",
    "name": "Pre-Construction Meeting",
    "start_date": "2025-03-01",
    "end_date": "2025-03-01",
    "predecessor_ids": [
      "s-caldwell-002"
    ],
    "percent_complete": 1,
    "status": "complete",
    "is_milestone": true
  },
  {
    "id": "s-caldwell-004",
    "job_id": "j-caldwell-1",
    "name": "Site Clearing + Grading",
    "start_date": "2025-03-15",
    "end_date": "2025-04-05",
    "predecessor_ids": [
      "s-caldwell-003"
    ],
    "percent_complete": 1,
    "status": "complete",
    "is_milestone": false,
    "assigned_vendor_id": "v-caldwell-bay-region-concrete"
  },
  {
    "id": "s-caldwell-005",
    "job_id": "j-caldwell-1",
    "name": "Foundation Casting",
    "start_date": "2025-04-08",
    "end_date": "2025-05-01",
    "predecessor_ids": [
      "s-caldwell-004"
    ],
    "percent_complete": 1,
    "status": "complete",
    "is_milestone": false,
    "assigned_vendor_id": "v-caldwell-bay-region-concrete"
  },
  {
    "id": "s-caldwell-006",
    "job_id": "j-caldwell-1",
    "name": "Foundation Inspection",
    "start_date": "2025-05-02",
    "end_date": "2025-05-02",
    "predecessor_ids": [
      "s-caldwell-005"
    ],
    "percent_complete": 1,
    "status": "complete",
    "is_milestone": true
  },
  {
    "id": "s-caldwell-007",
    "job_id": "j-caldwell-1",
    "name": "First Floor Framing",
    "start_date": "2025-05-05",
    "end_date": "2025-06-10",
    "predecessor_ids": [
      "s-caldwell-006"
    ],
    "percent_complete": 1,
    "status": "complete",
    "is_milestone": false,
    "assigned_vendor_id": "v-caldwell-bay-region-carpentry"
  },
  {
    "id": "s-caldwell-008",
    "job_id": "j-caldwell-1",
    "name": "Second Floor Framing",
    "start_date": "2025-06-12",
    "end_date": "2025-07-20",
    "predecessor_ids": [
      "s-caldwell-007"
    ],
    "percent_complete": 1,
    "status": "complete",
    "is_milestone": false,
    "assigned_vendor_id": "v-caldwell-bay-region-carpentry"
  },
  {
    "id": "s-caldwell-009",
    "job_id": "j-caldwell-1",
    "name": "Roof Trusses + Decking",
    "start_date": "2025-07-22",
    "end_date": "2025-08-15",
    "predecessor_ids": [
      "s-caldwell-008"
    ],
    "percent_complete": 1,
    "status": "complete",
    "is_milestone": false,
    "assigned_vendor_id": "v-caldwell-bay-region-carpentry"
  },
  {
    "id": "s-caldwell-010",
    "job_id": "j-caldwell-1",
    "name": "Dry-In Inspection",
    "start_date": "2025-08-18",
    "end_date": "2025-08-18",
    "predecessor_ids": [
      "s-caldwell-009"
    ],
    "percent_complete": 1,
    "status": "complete",
    "is_milestone": true
  },
  {
    "id": "s-caldwell-011",
    "job_id": "j-caldwell-1",
    "name": "Plumbing Rough-In",
    "start_date": "2025-08-20",
    "end_date": "2025-09-25",
    "predecessor_ids": [
      "s-caldwell-010"
    ],
    "percent_complete": 0.95,
    "status": "in_progress",
    "is_milestone": false,
    "assigned_vendor_id": "v-caldwell-anchor-bay-plumbing"
  },
  {
    "id": "s-caldwell-012",
    "job_id": "j-caldwell-1",
    "name": "Electrical Rough",
    "start_date": "2025-08-25",
    "end_date": "2025-10-05",
    "predecessor_ids": [
      "s-caldwell-010"
    ],
    "percent_complete": 0.85,
    "status": "in_progress",
    "is_milestone": false
  },
  {
    "id": "s-caldwell-013",
    "job_id": "j-caldwell-1",
    "name": "HVAC Rough + Equipment",
    "start_date": "2025-09-01",
    "end_date": "2025-10-15",
    "predecessor_ids": [
      "s-caldwell-010"
    ],
    "percent_complete": 0.7,
    "status": "in_progress",
    "is_milestone": false
  },
  {
    "id": "s-caldwell-014",
    "job_id": "j-caldwell-1",
    "name": "Smart Home Low Voltage",
    "start_date": "2025-09-15",
    "end_date": "2025-10-20",
    "predecessor_ids": [
      "s-caldwell-012"
    ],
    "percent_complete": 0.6,
    "status": "in_progress",
    "is_milestone": false,
    "assigned_vendor_id": "v-caldwell-coastal-smart-systems"
  },
  {
    "id": "s-caldwell-015",
    "job_id": "j-caldwell-1",
    "name": "Spray Foam Insulation",
    "start_date": "2025-10-22",
    "end_date": "2025-11-05",
    "predecessor_ids": [
      "s-caldwell-011",
      "s-caldwell-012",
      "s-caldwell-013"
    ],
    "percent_complete": 0.5,
    "status": "in_progress",
    "is_milestone": false,
    "assigned_vendor_id": "v-caldwell-coastline-foam"
  },
  {
    "id": "s-caldwell-016",
    "job_id": "j-caldwell-1",
    "name": "Drywall Hang + Finish",
    "start_date": "2025-11-10",
    "end_date": "2025-12-15",
    "predecessor_ids": [
      "s-caldwell-015"
    ],
    "percent_complete": 0.2,
    "status": "in_progress",
    "is_milestone": false,
    "assigned_vendor_id": "v-caldwell-sandhill-drywall"
  },
  {
    "id": "s-caldwell-017",
    "job_id": "j-caldwell-1",
    "name": "Tile — Floor + Wall",
    "start_date": "2025-12-18",
    "end_date": "2026-01-20",
    "predecessor_ids": [
      "s-caldwell-016"
    ],
    "percent_complete": 0,
    "status": "not_started",
    "is_milestone": false,
    "assigned_vendor_id": "v-caldwell-sand-dollar-tile"
  },
  {
    "id": "s-caldwell-018",
    "job_id": "j-caldwell-1",
    "name": "Cabinetry + Built-ins",
    "start_date": "2025-12-20",
    "end_date": "2026-02-05",
    "predecessor_ids": [
      "s-caldwell-016"
    ],
    "percent_complete": 0,
    "status": "not_started",
    "is_milestone": false
  },
  {
    "id": "s-caldwell-019",
    "job_id": "j-caldwell-1",
    "name": "Trim + Millwork",
    "start_date": "2026-01-15",
    "end_date": "2026-02-15",
    "predecessor_ids": [
      "s-caldwell-018"
    ],
    "percent_complete": 0,
    "status": "not_started",
    "is_milestone": false
  },
  {
    "id": "s-caldwell-020",
    "job_id": "j-caldwell-1",
    "name": "Painting + Coatings",
    "start_date": "2026-01-20",
    "end_date": "2026-02-20",
    "predecessor_ids": [
      "s-caldwell-019"
    ],
    "percent_complete": 0,
    "status": "not_started",
    "is_milestone": false,
    "assigned_vendor_id": "v-caldwell-bayside-painting"
  },
  {
    "id": "s-caldwell-021",
    "job_id": "j-caldwell-1",
    "name": "Plumbing Trim + Fixtures",
    "start_date": "2026-02-01",
    "end_date": "2026-02-25",
    "predecessor_ids": [
      "s-caldwell-017"
    ],
    "percent_complete": 0,
    "status": "not_started",
    "is_milestone": false,
    "assigned_vendor_id": "v-caldwell-anchor-bay-plumbing"
  },
  {
    "id": "s-caldwell-022",
    "job_id": "j-caldwell-1",
    "name": "Electrical Trim + Finish",
    "start_date": "2026-02-05",
    "end_date": "2026-03-01",
    "predecessor_ids": [
      "s-caldwell-020"
    ],
    "percent_complete": 0,
    "status": "not_started",
    "is_milestone": false
  },
  {
    "id": "s-caldwell-023",
    "job_id": "j-caldwell-1",
    "name": "Substantial Completion",
    "start_date": "2026-03-15",
    "end_date": "2026-03-15",
    "predecessor_ids": [
      "s-caldwell-022"
    ],
    "percent_complete": 0,
    "status": "not_started",
    "is_milestone": true
  },
  {
    "id": "s-caldwell-024",
    "job_id": "j-caldwell-1",
    "name": "Final Walk + Punch List",
    "start_date": "2026-03-20",
    "end_date": "2026-03-30",
    "predecessor_ids": [
      "s-caldwell-023"
    ],
    "percent_complete": 0,
    "status": "not_started",
    "is_milestone": false
  },
  {
    "id": "s-caldwell-025",
    "job_id": "j-caldwell-1",
    "name": "Certificate of Occupancy",
    "start_date": "2026-04-05",
    "end_date": "2026-04-05",
    "predecessor_ids": [
      "s-caldwell-024"
    ],
    "percent_complete": 0,
    "status": "not_started",
    "is_milestone": true
  }
];
