// Sanitized Caldwell fixture — generated by scripts/sanitize-drummond.ts
// Source: SUBSTITUTION-MAP vendor table + invoices-batch-caldwell-2025-11.pdf
// Generated: 2026-05-04
// Substitutions applied per .planning/fixtures/drummond/SUBSTITUTION-MAP.md (gitignored)
//
// DO NOT HAND-EDIT. Re-run `npx tsx scripts/sanitize-drummond.ts` to regenerate.

import type { CaldwellVendor } from "./types";

export const CALDWELL_VENDORS: CaldwellVendor[] = [
  {
    "id": "v-caldwell-coastal-smart-systems",
    "name": "Coastal Smart Systems LLC",
    "address": "2104 Coastal Way, Bradenton, FL 34208",
    "phone": "(941) 555-0301",
    "email": "contact@coastalsmartsystems.example",
    "default_cost_code_id": "cc-13101"
  },
  {
    "id": "v-caldwell-bay-region-carpentry",
    "name": "Bay Region Carpentry Inc",
    "address": "418 Bay Region Dr, Sarasota, FL 34243",
    "phone": "(941) 555-0302",
    "email": "contact@bayregioncarpentry.example",
    "default_cost_code_id": "cc-06101"
  },
  {
    "id": "v-caldwell-sandhill-drywall",
    "name": "Sandhill Drywall Inc",
    "address": "812 Sandhill Trail, Bradenton, FL 34203",
    "phone": "(941) 555-0303",
    "email": "contact@sandhilldrywall.example",
    "default_cost_code_id": "cc-15101"
  },
  {
    "id": "v-caldwell-coastline-foam",
    "name": "Coastline Foam LLC",
    "address": "519 Coastline Ave, Palmetto, FL 34221",
    "phone": "(941) 555-0304",
    "email": "contact@coastlinefoam.example",
    "default_cost_code_id": "cc-08101"
  },
  {
    "id": "v-caldwell-bayside-doors",
    "name": "Bayside Doors Inc",
    "address": "207 Bayside Pkwy, Bradenton, FL 34209",
    "phone": "(941) 555-0305",
    "email": "contact@baysidedoors.example",
    "default_cost_code_id": "cc-14201"
  },
  {
    "id": "v-caldwell-coastal-finishes",
    "name": "Coastal Finishes LLC",
    "address": "316 Coastal Finishes Way, Bradenton, FL 34210",
    "phone": "(941) 555-0306",
    "email": "contact@coastalfinishes.example",
    "default_cost_code_id": "cc-15101"
  },
  {
    "id": "v-caldwell-anchor-bay-plumbing",
    "name": "Anchor Bay Plumbing Inc",
    "address": "925 Anchor Bay Rd, Bradenton, FL 34211",
    "phone": "(941) 555-0307",
    "email": "contact@anchorbayplumbing.example",
    "default_cost_code_id": "cc-10101"
  },
  {
    "id": "v-caldwell-sun-coast-lumber",
    "name": "Sun Coast Lumber Co",
    "address": "1402 Sun Coast Blvd, Sarasota, FL 34233",
    "phone": "(941) 555-0308",
    "email": "contact@suncoastlumber.example",
    "default_cost_code_id": "cc-16101"
  },
  {
    "id": "v-caldwell-tide-mark-coatings",
    "name": "Tide Mark Coatings LLC",
    "address": "608 Tide Mark Way, Bradenton, FL 34212",
    "phone": "(941) 555-0309",
    "email": "contact@tidemarkcoatings.example",
    "default_cost_code_id": "cc-15501"
  },
  {
    "id": "v-caldwell-manatee-eco",
    "name": "Manatee Eco Co",
    "address": "714 Manatee Eco Dr, Bradenton, FL 34213",
    "phone": "(941) 555-0310",
    "email": "contact@manateeeco.example",
    "default_cost_code_id": "cc-08101"
  },
  {
    "id": "v-caldwell-mj-bay",
    "name": "MJ Bay Co",
    "address": "503 MJ Bay Trail, Sarasota, FL 34234",
    "phone": "(941) 555-0311",
    "email": "contact@mjbay.example",
    "default_cost_code_id": "cc-15201"
  },
  {
    "id": "v-caldwell-sand-dollar-tile",
    "name": "Sand Dollar Tile Co",
    "address": "812 Sand Dollar Ave, Bradenton, FL 34214",
    "phone": "(941) 555-0312",
    "email": "contact@sanddollartile.example",
    "default_cost_code_id": "cc-15201"
  },
  {
    "id": "v-caldwell-bayside-painting",
    "name": "Bayside Painting LLC",
    "address": "919 Bayside Painting Blvd, Sarasota, FL 34235",
    "phone": "(941) 555-0313",
    "email": "contact@baysidepainting.example",
    "default_cost_code_id": "cc-15501"
  },
  {
    "id": "v-caldwell-coastline-roofing",
    "name": "Coastline Roofing Inc",
    "address": "1006 Coastline Roof Rd, Bradenton, FL 34215",
    "phone": "(941) 555-0314",
    "email": "contact@coastlineroofing.example",
    "default_cost_code_id": "cc-07101"
  },
  {
    "id": "v-caldwell-bay-region-concrete",
    "name": "Bay Region Concrete Co",
    "address": "1418 Bay Region Concrete Way, Bradenton, FL 34216",
    "phone": "(941) 555-0315",
    "email": "contact@bayregionconcrete.example",
    "default_cost_code_id": "cc-05101"
  },
  {
    "id": "v-caldwell-ferguson",
    "name": "Ferguson",
    "address": "Ferguson Enterprises, FL Branch",
    "phone": "(800) 555-0001",
    "email": "contact@ferguson.example",
    "default_cost_code_id": "cc-10101"
  },
  {
    "id": "v-caldwell-fpl",
    "name": "FPL",
    "address": "Florida Power & Light, FL",
    "phone": "(800) 555-0002",
    "email": "contact@fpl.example",
    "default_cost_code_id": "cc-03110"
  },
  {
    "id": "v-caldwell-home-depot",
    "name": "Home Depot",
    "address": "Home Depot, Bradenton FL Branch",
    "phone": "(800) 555-0003",
    "email": "contact@homedepot.example",
    "default_cost_code_id": "cc-16101"
  }
];
